"""Stage 6: end-to-end community feed builder.

Orchestrates the full Discover → Correlate → Score → (Recommend) pipeline for
the validated source set defined in ``configs/community_public_sources.json``
and publishes a ready-to-serve feed directory.

Typical invocation::

    advisoryops community-build --set-id gold_pass1 --out-root-community outputs/community_public

What it does
------------
1. (Optional ``--refresh``) Runs ``source_run`` for each source in the selected
   validated set to pull new items before building.
2. Runs ``correlate`` across all discover outputs for the validated source IDs,
   writing intermediate results to ``<out_root_community>/correlate/``.
3. Runs ``score_issues`` on the correlated issues, writing to
   ``<out_root_community>/scored/``.
4. Builds the public feed artifacts (see outputs below).
5. (Optional ``--recommend``) Generates JSON remediation packets for P0/P1 alerts
   via the ``recommend_mitigations`` engine.

Output artifacts (all under ``out_root_community/``)::

    issues_public.jsonl      — all scored issues (full feed, sorted by score desc)
    alerts_public.jsonl      — high-priority subset (≥ min_priority)
    feed_latest.json         — most recent N issues as a JSON array (for the dashboard)
    feed.csv                 — spreadsheet-friendly export of all issues
    validated_sources.json   — source registry snapshot (validated + candidates)
    meta.json                — build metadata (params, counts, timestamps)
    packets/                 — per-issue JSON remediation packets (if --recommend)

The dashboard (``dashboard.html``) is generated by ``_generate_dashboard()``
and written alongside the other feed artifacts.  It loads feed_latest.json
and alerts_public.jsonl from the same directory via fetch().
"""
from __future__ import annotations

import csv
import json
import shutil
import xml.etree.ElementTree as ET
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Callable, Dict, Iterable, List, Optional, Sequence, Tuple

from .community_manifest import load_community_manifest
from .correlate import correlate
from .score import score_issues
from .source_run import source_run
from .sources_config import load_sources_config


def _read_jsonl(path: Path) -> List[Dict[str, Any]]:
    rows: List[Dict[str, Any]] = []
    if not path.exists():
        raise FileNotFoundError(f"Missing JSONL file: {path}")
    for line in path.read_text(encoding="utf-8", errors="replace").splitlines():
        line = line.strip()
        if not line:
            continue
        obj = json.loads(line)
        if isinstance(obj, dict):
            rows.append(obj)
    return rows


def _write_jsonl(path: Path, rows: Iterable[Dict[str, Any]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8", newline="\n") as f:
        for row in rows:
            f.write(json.dumps(row, ensure_ascii=False, sort_keys=True) + "\n")


def _feed_entry(issue: Dict[str, Any]) -> Dict[str, Any]:
    entry: Dict[str, Any] = {
        "issue_id": issue.get("issue_id", ""),
        "issue_type": issue.get("issue_type", ""),
        "title": issue.get("title", ""),
        "summary": issue.get("summary", ""),
        "canonical_link": issue.get("canonical_link", ""),
        "cves": issue.get("cves", []) or [],
        "sources": issue.get("sources", []) or [],
        "published_dates": issue.get("published_dates", []) or [],
        "first_seen_at": issue.get("first_seen_at", ""),
        "last_seen_at": issue.get("last_seen_at", ""),
        "score": int(issue.get("score", 0) or 0),
        "priority": issue.get("priority", ""),
        "actions": issue.get("actions", []) or [],
        "why": issue.get("why", []) or [],
        # Trust layer fields (gracefully default to empty when absent)
        "handling_warnings": issue.get("handling_warnings", []) or [],
        "evidence_gaps": issue.get("evidence_gaps", []) or [],
        "unknowns": issue.get("unknowns", []) or [],
        "source_consensus": issue.get("source_consensus") or {},
        "source_authority_weight": issue.get("source_authority_weight", 0),
        "highest_authority_source": issue.get("highest_authority_source", ""),
        "healthcare_category": issue.get("healthcare_category", ""),
        "classification": issue.get("classification") or {},
        "severity": issue.get("severity", ""),
        "affected_versions": issue.get("affected_versions", []) or [],
        "vendor": issue.get("vendor", ""),
        "generated_by": issue.get("generated_by", "deterministic"),
        # Provenance fields from AI classification / recommendation
        "extracted_facts": issue.get("extracted_facts") or {},
        "inferred_facts": issue.get("inferred_facts") or {},
        "confidence_by_field": issue.get("confidence_by_field") or {},
        "evidence_sources": issue.get("evidence_sources") or [],
        "insufficient_evidence": issue.get("insufficient_evidence", False),
        "non_applicability": issue.get("non_applicability") or [],
        # Source-cited mitigations and IOCs
        "source_mitigations": issue.get("source_mitigations") or [],
        "iocs": issue.get("iocs") or [],
        # NVD enrichment fields
        "cvss_score": issue.get("cvss_score", 0),
        "cvss_severity": issue.get("cvss_severity", ""),
        "cvss_vector": issue.get("cvss_vector", ""),
        "cwe_ids": issue.get("cwe_ids") or [],
        "affected_products": issue.get("affected_products") or [],
        "nvd_description": issue.get("nvd_description", ""),
        "source_summary": issue.get("source_summary", ""),
        # KEV-specific fields
        "kev_required_action": issue.get("kev_required_action", ""),
        "kev_due_date": issue.get("kev_due_date", ""),
        # Human-readable remediation
        "remediation_steps": issue.get("remediation_steps") or [],
        # Healthcare relevance tag
        "healthcare_relevant": bool(issue.get("healthcare_relevant", False)),
        # FDA device risk classification
        "fda_risk_class": issue.get("fda_risk_class") or None,
        # KEV + medical device cross-reference
        "is_kev_medical_device": bool(issue.get("is_kev_medical_device", False)),
    }
    return entry


def _sort_feed_entries(rows: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
    return sorted(
        rows,
        key=lambda r: (
            -int(r.get("score", 0) or 0),
            str(r.get("last_seen_at", "") or ""),
            str(r.get("issue_id", "") or ""),
        ),
    )


def _rss_pub_date(date_str: str) -> str:
    """Convert YYYY-MM-DD (or ISO 8601) to RFC 2822 for RSS pubDate."""
    if not date_str:
        return ""
    # Strip time portion if present
    ds = date_str[:10]
    try:
        dt = datetime(int(ds[0:4]), int(ds[5:7]), int(ds[8:10]), tzinfo=timezone.utc)
        return dt.strftime("%a, %d %b %Y %H:%M:%S +0000")
    except (ValueError, IndexError):
        return ""


def _write_rss(
    path: Path,
    rows: List[Dict[str, Any]],
    *,
    top: int = 50,
    title: str = "AdvisoryOps Community Feed",
    description: str = "Top-scored healthcare cybersecurity and device-safety advisories",
) -> None:
    """Write an RSS 2.0 feed of the top *top* scored issues and validate XML."""
    path.parent.mkdir(parents=True, exist_ok=True)

    channel = ET.Element("channel")

    ET.SubElement(channel, "title").text = title
    ET.SubElement(channel, "link").text = "https://github.com/advisoryops/advisoryops"
    ET.SubElement(channel, "description").text = description
    now_rfc = datetime.now(tz=timezone.utc).strftime("%a, %d %b %Y %H:%M:%S +0000")
    ET.SubElement(channel, "lastBuildDate").text = now_rfc
    ET.SubElement(channel, "language").text = "en-us"

    for issue in rows[:top]:
        item = ET.SubElement(channel, "item")

        ET.SubElement(item, "title").text = issue.get("title") or ""

        link = issue.get("canonical_link") or ""
        ET.SubElement(item, "link").text = link
        ET.SubElement(item, "guid").text = link or issue.get("issue_id", "")

        published_dates = issue.get("published_dates") or []
        first_date = published_dates[0] if published_dates else ""
        pub_date = _rss_pub_date(first_date)
        if pub_date:
            ET.SubElement(item, "pubDate").text = pub_date

        summary = (issue.get("summary") or "")[:500]
        ET.SubElement(item, "description").text = summary

        priority = issue.get("priority") or ""
        if priority:
            ET.SubElement(item, "category").text = priority

    rss_root = ET.Element("rss", version="2.0")
    rss_root.append(channel)

    xml_bytes = b'<?xml version="1.0" encoding="UTF-8"?>\n' + ET.tostring(
        rss_root, encoding="unicode"
    ).encode("utf-8")

    # Validate before writing
    ET.fromstring(xml_bytes)

    path.write_bytes(xml_bytes)


def _write_csv(path: Path, rows: List[Dict[str, Any]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    fieldnames = [
        "issue_id",
        "issue_type",
        "priority",
        "score",
        "title",
        "canonical_link",
        "cves",
        "sources",
        "published_dates",
        "first_seen_at",
        "last_seen_at",
    ]
    with path.open("w", encoding="utf-8", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        for row in rows:
            writer.writerow(
                {
                    "issue_id": row.get("issue_id", ""),
                    "issue_type": row.get("issue_type", ""),
                    "priority": row.get("priority", ""),
                    "score": row.get("score", 0),
                    "title": row.get("title", ""),
                    "canonical_link": row.get("canonical_link", ""),
                    "cves": ";".join(row.get("cves", []) or []),
                    "sources": ";".join(row.get("sources", []) or []),
                    "published_dates": ";".join(row.get("published_dates", []) or []),
                    "first_seen_at": row.get("first_seen_at", ""),
                    "last_seen_at": row.get("last_seen_at", ""),
                }
            )


def _generate_dashboard(path: Path) -> None:
    """Write the static dashboard HTML file to *path*.

    The dashboard loads ``feed_latest.json``, ``alerts_public.jsonl``, and
    ``meta.json`` via ``fetch()`` from the same directory.  All trust-layer
    sections (handling warnings, evidence gaps, source consensus, evidence
    completeness, extracted/inferred badges, source authority) are rendered
    in the detail panel and gracefully hidden when data is absent.
    """
    html = _DASHBOARD_HTML
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(html, encoding="utf-8", newline="\n")


def _deploy_docs(dashboard_path: Path, feed_path: Path, sources_path: Path) -> None:
    """Copy dashboard and data files to ``docs/`` for GitHub Pages deployment.

    Creates ``docs/index.html`` (renamed from dashboard.html),
    ``docs/feed_latest.json``, and ``docs/validated_sources.json``.
    """
    # Walk up from the dashboard to find the repo root (contains .git)
    repo_root: Optional[Path] = None
    candidate = dashboard_path.parent
    for _ in range(10):
        if (candidate / ".git").exists():
            repo_root = candidate
            break
        if candidate.parent == candidate:
            break
        candidate = candidate.parent

    if repo_root is None:
        # Fallback: use cwd or skip silently (e.g. during tests in tmp_path)
        return

    docs_dir = repo_root / "docs"
    docs_dir.mkdir(parents=True, exist_ok=True)

    shutil.copy2(str(dashboard_path), str(docs_dir / "index.html"))
    if feed_path.exists():
        shutil.copy2(str(feed_path), str(docs_dir / "feed_latest.json"))
    if sources_path.exists():
        shutil.copy2(str(sources_path), str(docs_dir / "validated_sources.json"))


# The dashboard template is defined as a module-level constant so tests can
# verify its content without invoking the full build pipeline.
_DASHBOARD_HTML = r'''<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>AdvisoryOps &mdash; Healthcare Advisory Intelligence</title>
<style>
*,*::before,*::after{box-sizing:border-box;margin:0;padding:0}
:root{
  --bg:#1a1a1a;--bg2:#222;--bg3:#2a2a2a;
  --text:#e8e8e8;--text2:#999;--text3:#666;
  --border:rgba(255,255,255,0.08);--border2:rgba(255,255,255,0.15);
  --p0-bg:#501313;--p0-text:#F09595;
  --p1-bg:#412402;--p1-text:#FAC775;
  --p2-bg:#27500A;--p2-text:#C0DD97;
  --p3-bg:#333;--p3-text:#999;
  --tag-ai-bg:#E6F1FB;--tag-ai-text:#0C447C;
  --tag-det-bg:#333;--tag-det-text:#666;
  --tag-warn-bg:#FAEEDA;--tag-warn-text:#854F0B;
  --tag-src-bg:#EAF3DE;--tag-src-text:#27500A;
  --fric-low-bg:#EAF3DE;--fric-low-text:#27500A;
  --fric-med-bg:#FAEEDA;--fric-med-text:#854F0B;
  --fric-high-bg:#FCEBEB;--fric-high-text:#791F1F;
  --gold:#EF9F27;--dot-empty:#444;
  --score-p0:#E24B4A;--score-p1:#EF9F27;--score-p2:#97C459;--score-p3:#666;
  --ev-green:#639922;--ev-yellow:#EF9F27;--ev-red:#E24B4A;
  --font:-apple-system,BlinkMacSystemFont,"Segoe UI",system-ui,sans-serif;
  --mono:"SFMono-Regular",Consolas,"Liberation Mono",monospace;
}
@media(prefers-color-scheme:light){
  :root{
    --bg:#fff;--bg2:#f8f8f6;--bg3:#f0efe8;
    --text:#1a1a1a;--text2:#666;--text3:#999;
    --border:rgba(0,0,0,0.08);--border2:rgba(0,0,0,0.15);
    --dot-empty:#ddd;--tag-det-bg:#f0f0f0;--tag-det-text:#666;
    --p3-bg:#f0f0f0;--p3-text:#999;
  }
}
html{scroll-behavior:smooth}
body{font-family:var(--font);background:var(--bg);color:var(--text);font-size:13px;line-height:1.6;min-width:320px}
a{color:#4A90D9;text-decoration:none}
a:hover{opacity:.8}

/* header */
.hdr{display:flex;align-items:center;padding:12px 20px;border-bottom:.5px solid var(--border)}
.hdr-logo{display:flex;align-items:baseline;gap:6px;text-decoration:none}
.hdr-name{font-size:17px;font-weight:500;color:var(--text)}
.hdr-sub{font-size:11px;color:var(--text2)}
.hdr-nav{display:flex;gap:2px;margin:0 auto}
.hdr-nav a{font-size:12px;padding:5px 10px;border-radius:8px;color:var(--text2)}
.hdr-nav a:hover,.hdr-nav a.active{background:var(--bg2);color:var(--text);text-decoration:none}
.hdr-right{display:flex;align-items:center;gap:10px;font-size:11px;color:var(--text2)}
.hdr-gh{font-size:11px;padding:4px 8px;border:.5px solid var(--border);border-radius:8px;color:#4A90D9}
.hdr-gh:hover{border-color:#4A90D9;text-decoration:none}

/* stats bar */
.stats{display:flex;align-items:center;gap:8px;padding:8px 20px;background:var(--bg2);border-bottom:.5px solid var(--border);flex-wrap:wrap}
.stat-chip{display:inline-flex;align-items:center;gap:5px;padding:4px 10px;font-size:11px;background:var(--bg);border:.5px solid var(--border);border-radius:8px}
.stat-chip b{font-variant-numeric:tabular-nums}
.stat-chip.p0 b{color:var(--p0-text)}.stat-chip.p1 b{color:var(--p1-text)}
.stat-chip.p2 b{color:var(--p2-text)}.stat-chip.p3 b{color:var(--p3-text)}
.stat-ts{margin-left:auto;font-size:11px;color:var(--text3)}

/* filter bar */
.filters{display:flex;align-items:center;gap:8px;padding:10px 20px;border-bottom:.5px solid var(--border);flex-wrap:wrap}
.search-input{flex:1;min-width:240px;font-size:13px;padding:7px 12px;border:.5px solid var(--border);border-radius:8px;background:var(--bg);color:var(--text);font-family:var(--font);outline:none}
.search-input:focus{border-color:#4A90D9}
.search-input::placeholder{color:var(--text3)}
.pill{font-size:11px;padding:4px 10px;border-radius:14px;border:.5px solid var(--border);background:transparent;color:var(--text2);cursor:pointer;font-family:var(--font);white-space:nowrap}
.pill:hover{border-color:var(--border2);color:var(--text)}
.pill.active{background:#E6F1FB;color:#0C447C;border-color:#85B7EB}
.pill.active.fp0{border-color:#791F1F;color:#F09595;background:transparent}
.pill.active.fp1{border-color:#633806;color:#FAC775;background:transparent}

/* issue cards */
.issues-list{padding:8px 20px}
.issue-card{border:.5px solid var(--border);border-radius:8px;overflow:hidden;margin:4px 0}
.issue-row{display:grid;grid-template-columns:48px 110px minmax(0,1fr) 72px 80px 80px 90px;padding:10px 16px;gap:8px;cursor:pointer;align-items:center}
.issue-row:hover{background:var(--bg2)}
.cell-label{display:block;font-size:9px;text-transform:uppercase;letter-spacing:.3px;color:var(--text3);line-height:1;margin-bottom:2px}
.pri-badge{display:inline-block;width:36px;text-align:center;padding:3px 0;border-radius:4px;font-size:11px;font-weight:500}
.pri-badge.p0{background:var(--p0-bg);color:var(--p0-text)}
.pri-badge.p1{background:var(--p1-bg);color:var(--p1-text)}
.pri-badge.p2{background:var(--p2-bg);color:var(--p2-text)}
.pri-badge.p3{background:var(--p3-bg);color:var(--p3-text)}
.issue-id-text{font-size:12px;font-weight:500;color:#4A90D9}
.issue-title-text{font-size:13px;font-weight:500;line-height:1.3}
.issue-vendor{font-size:11px;color:var(--text2);margin-top:1px}
.score-val{font-size:14px;font-weight:500;text-align:right;font-variant-numeric:tabular-nums}
.score-bar{height:3px;background:var(--bg3);border-radius:2px;margin-top:3px}
.score-fill{height:100%;border-radius:2px}
.auth-dots{display:flex;gap:3px;justify-content:center}
.auth-dot{width:7px;height:7px;border-radius:50%;background:var(--gold)}
.auth-dot.empty{background:var(--dot-empty)}
.tier-label{font-size:10px;color:var(--text3);text-align:center;margin-top:2px}
.ev-wrap{text-align:center}
.ev-bar{display:inline-block;width:48px;height:3px;background:var(--bg3);border-radius:2px;vertical-align:middle;overflow:hidden}
.ev-fill{height:100%;border-radius:2px}
.ev-num{font-size:11px;color:var(--text2);margin-left:4px;font-family:var(--mono)}
.analysis-tags{display:flex;gap:4px;justify-content:flex-end;flex-wrap:wrap}
.tag{display:inline-block;padding:2px 8px;border-radius:4px;font-size:10px;font-weight:500}
.tag-ai{background:var(--tag-ai-bg);color:var(--tag-ai-text)}
.tag-det{background:var(--tag-det-bg);color:var(--tag-det-text)}
.tag-warn{background:var(--tag-warn-bg);color:var(--tag-warn-text)}
.tag-src{background:var(--tag-src-bg);color:var(--tag-src-text)}

/* detail panel */
.detail-panel{border-top:.5px solid var(--border);padding:0 16px 16px}
.handling-warnings{border-left:3px solid #EF9F27;background:#FAEEDA;padding:10px 14px;margin:14px 0;border-radius:0}
.hw-title{font-size:11px;text-transform:uppercase;letter-spacing:.3px;color:#854F0B;font-weight:500;margin-bottom:4px}
.hw-list{margin:0;padding-left:16px;font-size:12px;color:#633806;line-height:1.6}
.detail-summary{font-size:13px;line-height:1.7;margin:12px 0 8px}
.detail-meta{display:flex;flex-wrap:wrap;gap:12px;font-size:11px;color:var(--text2);margin-bottom:16px}
.meta-contra{color:#BA7517}
.two-col{display:grid;grid-template-columns:minmax(0,1fr) minmax(0,1fr);gap:16px}
.col-hdr{display:flex;align-items:center;gap:8px;font-size:13px;font-weight:500;padding-bottom:8px;border-bottom:.5px solid var(--border);margin-bottom:10px}
.mit-card,.rec-card{border:.5px solid var(--border);border-radius:8px;padding:10px 12px;margin-bottom:6px}
.mit-hdr{display:flex;align-items:center;gap:8px;margin-bottom:4px;font-size:12px}
.mit-source{font-weight:500}
.tier-tag{font-size:10px;padding:2px 7px;border-radius:4px}
.tier-tag.t1{background:var(--tag-src-bg);color:var(--tag-src-text)}
.tier-tag.other{background:var(--bg2);color:var(--text2)}
.mit-action{font-size:12px;line-height:1.6}
.mit-cite{font-size:11px;color:var(--text2)}
.mit-link{font-size:11px;margin-top:3px}
.mit-empty,.rec-empty{font-size:12px;color:var(--text2);padding:8px 0}
.ioc-section{margin-top:14px}
.ioc-title{font-size:11px;text-transform:uppercase;letter-spacing:.3px;color:var(--text3);font-weight:500;margin-bottom:6px}
.ioc-item{display:flex;align-items:center;gap:8px;padding:4px 8px;background:var(--bg2);border-radius:4px;margin-bottom:3px;font-size:12px}
.ioc-type{font-size:10px;font-weight:500;background:var(--bg);border:.5px solid var(--border);border-radius:3px;min-width:38px;text-align:center;padding:1px 4px;text-transform:uppercase}
.ioc-val{font-family:var(--mono);font-size:11px;word-break:break-all}
.ioc-src{font-size:10px;color:var(--text2);margin-left:auto;white-space:nowrap}
.rec-hdr{display:flex;align-items:center;gap:8px;margin-bottom:4px;font-size:12px}
.rec-name{font-weight:500}
.fric-tag{font-size:10px;padding:2px 7px;border-radius:4px}
.fric-tag.low{background:var(--fric-low-bg);color:var(--fric-low-text)}
.fric-tag.medium{background:var(--fric-med-bg);color:var(--fric-med-text)}
.fric-tag.high{background:var(--fric-high-bg);color:var(--fric-high-text)}
.rec-rationale{font-size:11px;color:var(--text2);line-height:1.6}
.rec-basis{font-size:11px;color:var(--text2);font-style:italic}
.rec-side{font-size:11px;color:var(--text2);border-top:.5px solid var(--border);padding-top:6px;margin-top:6px}
.subsec-title{font-size:11px;text-transform:uppercase;letter-spacing:.3px;color:var(--text3);font-weight:500;margin:12px 0 4px}
.unknown-item{font-size:12px;color:var(--text2);padding:1px 0}
.consensus-ok{font-size:11px;color:#27500A}
.consensus-bad{font-size:11px;color:#BA7517}
.provenance-badges{margin-top:12px;display:flex;flex-direction:column;gap:4px}
.prov-row{display:flex;align-items:center;gap:6px;font-size:11px;color:var(--text2)}

/* action rows */
.action-rows{border-top:.5px solid var(--border);padding-top:12px;margin-top:16px;display:flex;flex-direction:column;gap:6px}
.action-row{display:flex;align-items:center}
.action-row-label{font-size:10px;font-weight:500;text-transform:uppercase;letter-spacing:.3px;color:var(--text3);width:88px;flex-shrink:0}
.action-row-btns{display:flex;flex-wrap:wrap;gap:4px}
.btn{padding:5px 11px;border:.5px solid var(--border);border-radius:6px;font-size:11px;background:var(--bg);color:var(--text2);cursor:pointer;font-family:var(--font)}
.btn:hover{border-color:var(--border2);color:var(--text)}
.btn:disabled{opacity:.35;cursor:not-allowed}
.btn:disabled:hover{border-color:var(--border);color:var(--text2)}
.btn-primary{background:#E6F1FB;color:#0C447C;border-color:#85B7EB}
.btn-primary:hover{opacity:.85}
.btn-warn{border-color:#EF9F27;color:#854F0B}
.btn-warn:hover{opacity:.85}
.btn-warn.flagged{opacity:.6;cursor:default}
.disclaimer-bar{font-size:11px;color:var(--text3);font-style:italic;line-height:1.6;margin-top:12px}

/* feedback dropdown */
.feedback-dropdown{position:relative;display:inline-block}
.feedback-btn{padding:5px 11px;border:.5px solid #EF9F27;border-radius:6px;font-size:11px;background:var(--bg);color:#854F0B;cursor:pointer;font-family:var(--font)}
.feedback-btn:hover{opacity:.85}
.feedback-btn.flagged{opacity:.6;cursor:default}
.feedback-menu{display:none;position:absolute;bottom:100%;left:0;background:var(--bg);border:.5px solid var(--border2);border-radius:8px;padding:4px 0;z-index:50;min-width:150px}
.feedback-menu.open{display:block}
.feedback-menu-item{display:block;width:100%;text-align:left;padding:5px 12px;font-size:11px;border:none;background:none;color:var(--text);cursor:pointer;font-family:var(--font)}
.feedback-menu-item:hover{background:var(--bg2)}

/* code overlay */
.code-overlay{position:fixed;inset:0;background:rgba(0,0,0,.6);z-index:200;display:flex;align-items:center;justify-content:center}
.code-box{background:var(--bg);border:.5px solid var(--border2);border-radius:8px;width:640px;max-height:80vh;display:flex;flex-direction:column}
.code-box-hdr{display:flex;justify-content:space-between;align-items:center;padding:10px 14px;border-bottom:.5px solid var(--border)}
.code-box-hdr span{font-size:13px;font-weight:500}
.code-box pre{flex:1;overflow:auto;padding:14px;font-family:var(--mono);font-size:11px;line-height:1.5;color:var(--text);white-space:pre-wrap;word-break:break-all}

/* sections */
.page-section{max-width:1400px;margin:0 auto;padding:24px 20px}
.section-heading{font-size:16px;font-weight:500;margin-bottom:16px}
.sources-table{width:100%;border-collapse:collapse}
.sources-table th{text-align:left;padding:6px 10px;font-size:11px;font-weight:500;color:var(--text2);text-transform:uppercase;letter-spacing:.3px;border-bottom:.5px solid var(--border);cursor:pointer}
.sources-table th:hover{color:var(--text)}
.sources-table td{padding:6px 10px;border-bottom:.5px solid var(--border);font-size:12px}
.sources-table tr:hover{background:var(--bg2)}
.prose{max-width:720px;font-size:13px;line-height:1.7;color:var(--text2)}
.prose h3{font-size:14px;font-weight:500;color:var(--text);margin:16px 0 4px}
.prose p{margin-bottom:10px}
.prose code{background:var(--bg2);padding:1px 5px;border-radius:3px;font-family:var(--mono);font-size:12px}

/* footer */
.site-footer{display:flex;justify-content:space-between;padding:16px 20px;border-top:.5px solid var(--border);font-size:11px;color:var(--text2);max-width:1400px;margin:0 auto}
.site-footer a{color:var(--text2)}
.site-footer a:hover{color:var(--text)}

/* sort arrow */
.sort-ind{font-size:9px;margin-left:2px;opacity:.5}
.sort-ind.on{opacity:1;color:#4A90D9}

/* loading / empty */
.state-msg{text-align:center;padding:48px 20px;color:var(--text2)}
.state-msg h2{font-size:15px;font-weight:500;color:var(--text);margin-bottom:6px}
.state-msg code{background:var(--bg2);padding:1px 5px;border-radius:3px;font-family:var(--mono);font-size:12px}

/* toast */
.toast{position:fixed;bottom:20px;right:20px;background:var(--bg);border:.5px solid #4A90D9;border-radius:8px;padding:8px 14px;font-size:12px;color:#4A90D9;z-index:300;opacity:0;transition:opacity .15s}
.toast.show{opacity:1}

/* table header row for sortable */
.tbl-hdr{display:grid;grid-template-columns:48px 110px minmax(0,1fr) 72px 80px 80px 90px;padding:6px 16px;gap:8px;font-size:11px;font-weight:500;text-transform:uppercase;letter-spacing:.3px;color:var(--text3);border-bottom:.5px solid var(--border);position:sticky;top:0;background:var(--bg);z-index:10}
.tbl-hdr span{cursor:pointer}
.tbl-hdr span:hover{color:var(--text)}
.tbl-hdr .h-score,.tbl-hdr .h-analysis{text-align:right}
.tbl-hdr .h-sources,.tbl-hdr .h-evidence{text-align:center}

/* mobile */
@media(max-width:768px){
  .hdr-nav{display:none}
  .stats{overflow-x:auto;flex-wrap:nowrap}
  .filters{flex-wrap:wrap}
  .search-input{min-width:0;width:100%}
  .pill{flex-shrink:0}
  .filter-pills-wrap{display:flex;overflow-x:auto;gap:6px;width:100%}
  .tbl-hdr{grid-template-columns:40px minmax(0,1fr) 56px}
  .tbl-hdr .h-sources,.tbl-hdr .h-evidence,.tbl-hdr .h-analysis{display:none}
  .issue-row{grid-template-columns:40px minmax(0,1fr) 56px}
  .issue-row .cell-sources,.issue-row .cell-evidence,.issue-row .cell-analysis{display:none}
  .two-col{grid-template-columns:1fr}
  .action-row{flex-direction:column;align-items:flex-start}
  .action-row-label{width:auto;margin-bottom:4px}
  .action-row-btns{width:100%;flex-direction:column}
  .action-row-btns .btn{width:100%}
  .sources-table-wrap{overflow-x:auto}
  .prose{padding:0 16px}
  .site-footer{flex-direction:column;gap:6px;text-align:center}
}
</style>
</head>
<body>

<header class="hdr">
  <a class="hdr-logo" href="#">
    <span class="hdr-name">AdvisoryOps</span>
    <span class="hdr-sub">healthcare advisory intelligence</span>
  </a>
  <nav class="hdr-nav">
    <a href="#issues-section" class="active">Issues</a>
    <a href="#sources-section">Sources</a>
    <a href="#methodology-section">Methodology</a>
    <a href="#about-section">About</a>
  </nav>
  <div class="hdr-right">
    <span id="hdr-issues"></span>
    <span id="hdr-sources"></span>
    <a class="hdr-gh" href="https://github.com/advisoryops/advisoryops" target="_blank" rel="noopener">GitHub</a>
  </div>
</header>

<div class="stats" id="stats-bar"></div>

<div class="filters" id="issues-section">
  <input class="search-input" type="text" placeholder="Search issues, CVEs, vendors, devices..." oninput="App.onSearch(this.value)">
  <div class="filter-pills-wrap" id="filter-pills"></div>
</div>

<div class="issues-list" id="issues-list">
  <div class="state-msg"><h2>Loading&hellip;</h2></div>
</div>

<div class="page-section" id="sources-section">
  <h2 class="section-heading">Sources</h2>
  <div class="sources-table-wrap" id="sources-wrap"><div class="state-msg">Loading sources&hellip;</div></div>
</div>

<div class="page-section" id="methodology-section">
  <h2 class="section-heading">Methodology</h2>
  <div class="prose">
    <h3>Healthcare-specific scoring</h3>
    <p>Issues are scored for healthcare impact, not generic CVSS severity. A critical vulnerability on a ventilator scores higher than the same CVE on a back-office workstation.</p>
    <h3>Source authority tiers</h3>
    <p>Sources are weighted by authority. Tier 1 (CISA, FDA) carries more weight than Tier 4 (news). When sources disagree, the higher-tier source's assessment is noted.</p>
    <h3>AI usage</h3>
    <p>AI extracts facts, normalizes data, compares sources, and recommends from approved mitigation patterns. It does not invent mitigations or replace vendor guidance.</p>
    <h3>Evidence completeness</h3>
    <p>Each issue is scored 0&ndash;8 based on which fields are populated: title, summary, CVEs, severity, affected versions, vendor, handling warnings, and multi-source confirmation.</p>
    <h3>Playbook governance</h3>
    <p>All mitigation patterns cite specific standards (NIST SP 800-82, IEC 62443, FDA guidance, CISA best practices). Patterns are reviewed before inclusion. AI-generated recommendations are constrained to approved patterns only. See <code>docs/playbook_governance.md</code> for details.</p>
  </div>
</div>

<div class="page-section" id="about-section">
  <h2 class="section-heading">About</h2>
  <div class="prose">
    <p>AdvisoryOps is an open-source advisory-to-action pipeline for healthcare cybersecurity. It monitors <span id="about-src-ct">0</span> public sources, normalizes and deduplicates advisories, scores them for healthcare impact, and generates actionable defensive guidance.</p>
    <p>The AI extracts, normalizes, compares, and recommends from approved mitigation patterns. It does not replace vendor guidance or make final operational decisions. All recommendations must be verified against vendor documentation before implementation in clinical environments.</p>
    <p><span id="about-issue-ct">0</span> issues &middot; <span id="about-src-ct2">0</span> sources &middot; <span id="about-pkt-ct">0</span> remediation packets</p>
    <p>License: Apache 2.0 &middot; <a href="https://github.com/advisoryops/advisoryops" target="_blank" rel="noopener">GitHub</a></p>
    <p>Built by Travis Funkhouser</p>
  </div>
</div>

<footer class="site-footer" id="site-footer">
  <div>AdvisoryOps &middot; Apache 2.0 &middot; <a href="https://github.com/advisoryops/advisoryops" target="_blank" rel="noopener">GitHub</a> &middot; Built by Travis Funkhouser</div>
  <div id="footer-meta"></div>
</footer>

<div class="toast" id="toast"></div>

<script>
(function(){
"use strict";
var $=function(id){return document.getElementById(id)};
var escEl=document.createElement("div");
function esc(s){if(s==null)return"";escEl.textContent=String(s);return escEl.innerHTML}
function showToast(m,ms){var t=$("toast");t.textContent=m;t.classList.add("show");setTimeout(function(){t.classList.remove("show")},ms||2000)}
function copyText(t){if(navigator.clipboard){navigator.clipboard.writeText(t).then(function(){showToast("Copied to clipboard")})}else{showToast("Clipboard not available")}}
function downloadFile(name,content,mime){var b=new Blob([content],{type:mime||"application/octet-stream"});var a=document.createElement("a");a.href=URL.createObjectURL(b);a.download=name;a.click();URL.revokeObjectURL(a.href)}

/* state */
var S={
  issues:[],sources:[],search:"",
  filters:{priority:"",hasWarnings:false,multiSource:false,hasIocs:false,contradictions:false},
  expanded:null,sortCol:"score",sortDir:-1,
  srcSortCol:"source_id",srcSortDir:1
};

/* load */
Promise.all([
  fetch("feed_latest.json").then(function(r){return r.json()}),
  fetch("validated_sources.json").then(function(r){return r.json()}).catch(function(){return[]})
]).then(function(res){
  S.issues=res[0]||[];S.sources=res[1]||[];
  renderAll();
}).catch(function(err){
  $("issues-list").innerHTML='<div class="state-msg"><h2>Could not load data</h2><p>'+esc(err.message)+'</p><p>Run <code>python -m http.server 8080</code> from <code>outputs/community_public/</code></p></div>';
});

/* evidence */
var EV_FIELDS=["title","summary","cves","severity","affected_versions","vendor","handling_warnings","sources"];
function evScore(r){var n=0;EV_FIELDS.forEach(function(f){var v=r[f];if(Array.isArray(v)){if(v.length)n++}else if(v)n++});return n}
function evColor(n){return n>=7?"var(--ev-green)":n>=5?"var(--ev-yellow)":"var(--ev-red)"}

/* authority */
function tierNum(r){var w=r.source_authority_weight;if(w>=1)return 1;if(w>=0.75)return 2;if(w>=0.5)return 3;return 4}
function tierDots(t){var filled=t===1?4:t===2?3:t===3?2:1;var h="";for(var i=0;i<4;i++)h+='<span class="auth-dot'+(i<filled?"":" empty")+'"></span>';return h}

/* score color */
function scoreColor(p){return p==="P0"?"var(--score-p0)":p==="P1"?"var(--score-p1)":p==="P2"?"var(--score-p2)":"var(--score-p3)"}

/* filter/sort */
function filterIssues(){
  var s=S.search.toLowerCase();
  return S.issues.filter(function(r){
    if(s){var hay=((r.issue_id||"")+" "+(r.title||"")+" "+(r.summary||"")+" "+(r.cves||[]).join(" ")+" "+(r.sources||[]).join(" ")+" "+(r.vendor||"")).toLowerCase();if(hay.indexOf(s)===-1)return false}
    var f=S.filters;
    if(f.priority&&r.priority!==f.priority)return false;
    if(f.hasWarnings&&!(r.handling_warnings&&r.handling_warnings.length))return false;
    if(f.multiSource&&(r.sources||[]).length<2)return false;
    if(f.hasIocs&&!(r.iocs&&r.iocs.length))return false;
    if(f.contradictions){var sc=r.source_consensus||{};if(!(sc.contradicted&&sc.contradicted.length))return false}
    return true;
  });
}
function sortIssues(rows){
  var col=S.sortCol,dir=S.sortDir;
  return rows.slice().sort(function(a,b){
    var va,vb;
    if(col==="score"){va=a.score||0;vb=b.score||0}
    else if(col==="priority"){va=a.priority||"P9";vb=b.priority||"P9"}
    else if(col==="issue_id"){va=a.issue_id||"";vb=b.issue_id||""}
    else if(col==="title"){va=(a.title||"").toLowerCase();vb=(b.title||"").toLowerCase()}
    else if(col==="sources"){va=(a.sources||[]).length;vb=(b.sources||[]).length}
    else if(col==="evidence"){va=evScore(a);vb=evScore(b)}
    else{va=a[col]||"";vb=b[col]||""}
    if(va<vb)return -dir;if(va>vb)return dir;return 0;
  });
}

/* render all */
function renderAll(){renderHeader();renderStats();renderPills();renderTable();renderSources();renderAbout();renderFooter()}

function renderHeader(){
  $("hdr-issues").textContent=S.issues.length+" issues";
  $("hdr-sources").textContent=S.sources.length+" sources";
}

function renderStats(){
  var ct={P0:0,P1:0,P2:0,P3:0},pkts=0,contras=0,lastTs="";
  S.issues.forEach(function(r){
    ct[r.priority]=(ct[r.priority]||0)+1;
    if((r.actions||[]).length)pkts++;
    var sc=r.source_consensus||{};if(sc.contradicted&&sc.contradicted.length)contras++;
    var ls=r.last_seen_at||"";if(ls>lastTs)lastTs=ls;
  });
  var h='<span class="stat-chip p0"><b>'+ct.P0+'</b> P0</span>'
    +'<span class="stat-chip p1"><b>'+ct.P1+'</b> P1</span>'
    +'<span class="stat-chip p2"><b>'+ct.P2+'</b> P2</span>'
    +'<span class="stat-chip p3"><b>'+ct.P3+'</b> P3</span>'
    +'<span class="stat-chip"><b>'+pkts+'</b> packets</span>'
    +'<span class="stat-chip"><b>'+contras+'</b> contradictions</span>';
  if(lastTs)h+='<span class="stat-ts">Updated '+esc(lastTs.slice(0,16).replace("T"," "))+'</span>';
  $("stats-bar").innerHTML=h;
}

var PILL_DEFS=[
  {label:"All",key:"priority",val:""},
  {label:"P0",key:"priority",val:"P0"},
  {label:"P1",key:"priority",val:"P1"},
  {label:"P2",key:"priority",val:"P2"},
  {label:"P3",key:"priority",val:"P3"},
  {label:"Has warnings",key:"hasWarnings",val:true},
  {label:"Multi-source",key:"multiSource",val:true},
  {label:"Has IOCs",key:"hasIocs",val:true},
  {label:"Contradictions",key:"contradictions",val:true}
];

function renderPills(){
  var h="";
  PILL_DEFS.forEach(function(p,i){
    var active=false;
    if(p.key==="priority")active=S.filters.priority===p.val;
    else active=!!S.filters[p.key];
    var cls="pill"+(active?" active":"");
    if(active&&p.val==="P0")cls+=" fp0";
    if(active&&p.val==="P1")cls+=" fp1";
    h+='<span class="'+cls+'" onclick="App.toggleFilter('+i+')">'+p.label+'</span>';
  });
  $("filter-pills").innerHTML=h;
}

function sortArrow(col){
  if(S.sortCol!==col)return'<span class="sort-ind"></span>';
  return'<span class="sort-ind on">'+(S.sortDir===1?"\u25B2":"\u25BC")+'</span>';
}

function renderTable(){
  var rows=sortIssues(filterIssues());
  if(!rows.length){$("issues-list").innerHTML='<div class="state-msg"><h2>No issues match filters</h2></div>';return}
  var h='<div class="tbl-hdr">'
    +'<span onclick="App.setSort(\'priority\')">Priority'+sortArrow("priority")+'</span>'
    +'<span onclick="App.setSort(\'issue_id\')">Issue'+sortArrow("issue_id")+'</span>'
    +'<span onclick="App.setSort(\'title\')">Title'+sortArrow("title")+'</span>'
    +'<span class="h-score" onclick="App.setSort(\'score\')">Score'+sortArrow("score")+'</span>'
    +'<span class="h-sources" onclick="App.setSort(\'sources\')">Sources'+sortArrow("sources")+'</span>'
    +'<span class="h-evidence" onclick="App.setSort(\'evidence\')">Evidence'+sortArrow("evidence")+'</span>'
    +'<span class="h-analysis">Analysis</span>'
    +'</div>';
  rows.forEach(function(r){h+=renderIssueCard(r)});
  $("issues-list").innerHTML=h;
}

function renderIssueCard(r){
  var p=(r.priority||"P3").toLowerCase();
  var ev=evScore(r);var evPct=Math.round(ev/8*100);
  var tier=tierNum(r);
  var srcCt=(r.sources||[]).length;
  var genBy=r.generated_by||"deterministic";
  var hasWarn=(r.handling_warnings||[]).length>0;
  var sc=scoreColor(r.priority||"P3");
  var id_safe=esc((r.issue_id||"").replace(/'/g,""));
  var expanded=S.expanded===r.issue_id;

  var h='<div class="issue-card">';
  h+='<div class="issue-row" onclick="App.toggle(\''+id_safe+'\')">';
  h+='<div><span class="pri-badge '+p+'">'+esc(r.priority)+'</span></div>';
  h+='<div><span class="cell-label">'+(r.issue_type==="cve"?"cve":"id")+'</span><span class="issue-id-text">'+esc(r.issue_id)+'</span></div>';
  h+='<div><span class="issue-title-text">'+esc(r.title)+'</span>'+(r.vendor?'<div class="issue-vendor">'+esc(r.vendor)+'</div>':'')+'</div>';
  h+='<div><span class="score-val" style="color:'+sc+'">'+(r.score||0)+'</span><div class="score-bar"><div class="score-fill" style="width:'+Math.min(100,Math.round((r.score||0)/300*100))+'%;background:'+sc+'"></div></div></div>';
  h+='<div class="cell-sources"><div class="auth-dots">'+tierDots(tier)+'</div><div class="tier-label">Tier '+tier+'</div></div>';
  h+='<div class="cell-evidence ev-wrap"><div class="ev-bar"><div class="ev-fill" style="width:'+evPct+'%;background:'+evColor(ev)+'"></div></div><span class="ev-num">'+ev+'/8</span></div>';
  h+='<div class="cell-analysis"><div class="analysis-tags">';
  h+=genBy==="ai"?'<span class="tag tag-ai">AI-enriched</span>':'<span class="tag tag-det">Deterministic</span>';
  if(hasWarn)h+='<span class="tag tag-warn">warnings</span>';
  h+='</div></div>';
  h+='</div>'; /* end issue-row */

  if(expanded)h+=renderDetail(r);
  h+='</div>'; /* end issue-card */
  return h;
}

function renderDetail(r){
  var hw=r.handling_warnings||[];
  var sm=r.source_mitigations||[];
  var iocs=r.iocs||[];
  var actions=r.actions||[];
  var unknowns=(r.unknowns||[]).concat(r.evidence_gaps||[]);
  var sc=r.source_consensus||{};
  var genBy=r.generated_by||"deterministic";
  var cves=r.cves||[];
  var sources=r.sources||[];
  var ef=r.extracted_facts||{};
  var inf=r.inferred_facts||{};
  var na=r.non_applicability||[];

  /* dedupe unknowns */
  var seen={};unknowns=unknowns.filter(function(u){if(seen[u])return false;seen[u]=1;return true});

  var h='<div class="detail-panel">';

  /* handling warnings */
  if(hw.length){
    h+='<div class="handling-warnings"><div class="hw-title">Handling warnings</div><ul class="hw-list">';
    hw.forEach(function(w){h+='<li>'+esc(w)+'</li>'});
    h+='</ul></div>';
  }

  /* summary */
  h+='<div class="detail-summary">'+esc(r.summary||"No summary available.")+'</div>';

  /* meta */
  h+='<div class="detail-meta">';
  if(cves.length)h+='<span>'+cves.map(function(c){return'<a href="https://nvd.nist.gov/vuln/detail/'+encodeURIComponent(c)+'" target="_blank" rel="noopener">'+esc(c)+'</a>'}).join(", ")+'</span>';
  if(sources.length)h+='<span>'+sources.map(function(s){return esc(s)}).join(", ")+'</span>';
  h+='<span>'+esc(r.priority||"")+" &middot; Score "+(r.score||0)+'</span>';
  if(sc.contradicted&&sc.contradicted.length)h+='<span class="meta-contra">Contradictions found</span>';
  h+='</div>';

  /* two-col */
  h+='<div class="two-col">';

  /* LEFT */
  h+='<div class="source-mitigations-col">';
  h+='<div class="col-hdr">What sources recommend <span class="tag tag-src">Source-cited</span></div>';
  if(sm.length){
    sm.forEach(function(m){
      var t=m.source_tier||4;
      h+='<div class="mit-card"><div class="mit-hdr"><span class="mit-source">'+esc(m.source)+'</span><span class="tier-tag'+(t===1?" t1":" other")+'">Tier '+t+'</span></div>';
      h+='<div class="mit-action">'+esc(m.action)+'</div>';
      if(m.citation)h+='<div class="mit-cite">'+esc(m.citation)+'</div>';
      if(m.url)h+='<div class="mit-link"><a href="'+esc(m.url)+'" target="_blank" rel="noopener">View source</a></div>';
      h+='</div>';
    });
  } else {
    h+='<div class="mit-empty">No source-specific mitigations found for this issue. See our analysis for playbook-based guidance.</div>';
  }

  /* IOCs */
  if(iocs.length){
    h+='<div class="ioc-section"><div class="ioc-title">Published indicators</div>';
    iocs.forEach(function(ioc){
      h+='<div class="ioc-item"><span class="ioc-type">'+esc((ioc.type||"").toUpperCase())+'</span><span class="ioc-val">'+esc(ioc.value)+'</span><span class="ioc-src">'+esc(ioc.source)+'</span></div>';
    });
    h+='</div>';
  }
  h+='</div>'; /* end left */

  /* RIGHT */
  h+='<div class="analysis-col">';
  h+='<div class="col-hdr">Our analysis <span class="tag tag-ai">AI-assisted</span></div>';

  if(actions.length&&genBy==="ai"){
    actions.forEach(function(act){
      var friction=inf.friction_level||(act==="notify"||act==="ingest"?"low":"medium");
      var fc=friction==="low"?"low":friction==="high"?"high":"medium";
      h+='<div class="rec-card"><div class="rec-hdr"><span class="rec-name">'+esc(act)+'</span><span class="fric-tag '+fc+'">'+esc(friction)+' friction</span></div>';
      if(ef.rationale)h+='<div class="rec-rationale">'+esc(ef.rationale)+'</div>';
      if(ef.basis)h+='<div class="rec-basis">'+esc(ef.basis)+'</div>';
      if(inf.side_effects)h+='<div class="rec-side">Side effects: '+esc(inf.side_effects)+'</div>';
      h+='</div>';
    });
  } else if(actions.length){
    actions.forEach(function(act){
      h+='<div class="rec-card"><div class="rec-hdr"><span class="rec-name">'+esc(act)+'</span></div></div>';
    });
  } else {
    h+='<div class="rec-empty">Deterministic scoring only.</div>';
  }

  /* unknowns / evidence gaps */
  if(unknowns.length){
    h+='<div class="evidence-gaps"><div class="subsec-title">What we don\'t know</div>';
    unknowns.forEach(function(u){h+='<div class="unknown-item">&bull; '+esc(u)+'</div>'});
    h+='</div>';
  }

  /* consensus */
  if((sc.agreed&&sc.agreed.length)||(sc.contradicted&&sc.contradicted.length)){
    h+='<div class="source-consensus"><div class="subsec-title">Source consensus</div>';
    (sc.agreed||[]).forEach(function(a){h+='<div class="consensus-ok">&check; '+esc(a)+'</div>'});
    (sc.contradicted||[]).forEach(function(c){h+='<div class="consensus-bad">&cross; '+esc(c)+'</div>'});
    h+='</div>';
  }

  /* provenance */
  h+='<div class="provenance-badges">';
  if(genBy==="ai"){
    h+='<div class="prov-row"><span class="tag tag-ai">AI-enriched</span> Summary, recommendations, handling warnings</div>';
    h+='<div class="prov-row"><span class="tag tag-det">Deterministic</span> Score, priority, correlation</div>';
  } else {
    h+='<div class="prov-row"><span class="tag tag-det">Deterministic</span> Score, priority, correlation</div>';
  }
  h+='</div>';

  h+='</div>'; /* end right */
  h+='</div>'; /* end two-col */

  /* ACTION ROWS */
  var hasIocData=iocs.length>0;
  var id_safe=esc((r.issue_id||"").replace(/'/g,""));
  h+='<div class="action-rows">';
  h+=actRow("Remediate",[
    {label:"Copy action checklist",fn:"copyChecklist",id:id_safe,cls:"btn-primary"},
    {label:"Export packet (JSON)",fn:"exportJSON",id:id_safe},
    {label:"Export packet (Markdown)",fn:"exportMD",id:id_safe}
  ]);
  h+=actRow("Detect",[
    {label:"Generate Sigma rule",fn:"genSigma",id:id_safe,dis:!hasIocData},
    {label:"Generate Suricata rule",fn:"genSuricata",id:id_safe,dis:!hasIocData}
  ]);
  h+=actRow("Block / Hunt",[
    {label:"Copy IOCs (CSV)",fn:"copyIocsCsv",id:id_safe,dis:!hasIocData},
    {label:"Copy IOCs (STIX)",fn:"copyIocsStix",id:id_safe,dis:!hasIocData},
    {label:"Generate ACL",fn:"genAcl",id:id_safe,dis:!hasIocData}
  ]);
  h+=actRow("Sources",[
    {label:"View all source links",fn:"viewLinks",id:id_safe},
    {label:"View raw advisory text",fn:"viewRaw",id:id_safe}
  ]);
  /* feedback row with dropdown */
  h+='<div class="action-row"><span class="action-row-label">Feedback</span><div class="action-row-btns">';
  h+='<div class="feedback-dropdown"><button class="feedback-btn" onclick="event.stopPropagation();App.toggleFb(\''+id_safe+'\')">Flag this recommendation</button>';
  h+='<div id="fb_'+id_safe.replace(/[^a-z0-9]/gi,"_")+'" class="feedback-menu">';
  ["incorrect","too_aggressive","too_conservative","missing_context","helpful"].forEach(function(t){
    h+='<button class="feedback-menu-item" onclick="event.stopPropagation();App.submitFeedback(\''+id_safe+'\',\''+t+'\')">'+t.replace(/_/g," ")+'</button>';
  });
  h+='</div></div>';
  h+='<button class="btn" onclick="event.stopPropagation();App.reportIncorrect(\''+id_safe+'\')">Report incorrect data</button>';
  h+='</div></div>';
  h+='</div>'; /* end action-rows */

  /* disclaimer */
  h+='<div class="disclaimer-bar">AI-assisted guidance based on approved mitigation patterns and cited standards. Source mitigations are extracted from published advisories and attributed to their original authors. Verify against vendor documentation and local operational constraints before implementation.</div>';

  h+='</div>'; /* end detail-panel */
  return h;
}

function actRow(label,btns){
  var h='<div class="action-row"><span class="action-row-label">'+esc(label)+'</span><div class="action-row-btns">';
  btns.forEach(function(b){
    var cls="btn"+(b.cls?" "+b.cls:"");
    var dis=b.dis?" disabled":"";
    h+='<button class="'+cls+'"'+dis+' onclick="event.stopPropagation();App.'+b.fn+'(\''+b.id+'\')">'+esc(b.label)+'</button>';
  });
  h+='</div></div>';return h;
}

/* sources */
function renderSources(){
  if(!S.sources.length){$("sources-wrap").innerHTML='<div class="state-msg">No source data available.</div>';return}
  var rows=S.sources.slice().sort(function(a,b){
    var c=S.srcSortCol,d=S.srcSortDir;
    var va=a[c]||"",vb=b[c]||"";
    if(typeof va==="number"&&typeof vb==="number"){if(va<vb)return -d;if(va>vb)return d;return 0}
    va=String(va).toLowerCase();vb=String(vb).toLowerCase();
    if(va<vb)return -d;if(va>vb)return d;return 0;
  });
  function sa(c){return S.srcSortCol===c?'<span class="sort-ind on">'+(S.srcSortDir===1?"\u25B2":"\u25BC")+"</span>":""}
  var h='<table class="sources-table"><thead><tr>';
  h+='<th onclick="App.sortSrc(\'source_id\')">Source ID'+sa("source_id")+'</th>';
  h+='<th onclick="App.sortSrc(\'name\')">Name'+sa("name")+'</th>';
  h+='<th onclick="App.sortSrc(\'scope\')">Scope'+sa("scope")+'</th>';
  h+='<th onclick="App.sortSrc(\'status\')">Status'+sa("status")+'</th>';
  h+='</tr></thead><tbody>';
  rows.forEach(function(s){
    h+='<tr><td style="font-family:var(--mono);font-size:11px">'+esc(s.source_id)+'</td>';
    h+='<td>'+esc(s.name)+'</td><td>'+esc(s.scope)+'</td><td>'+esc(s.status)+'</td></tr>';
  });
  h+='</tbody></table>';
  $("sources-wrap").innerHTML=h;
}

function renderAbout(){
  var pkts=0;S.issues.forEach(function(r){if((r.actions||[]).length)pkts++});
  $("about-src-ct").textContent=S.sources.length;
  $("about-src-ct2").textContent=S.sources.length;
  $("about-issue-ct").textContent=S.issues.length;
  $("about-pkt-ct").textContent=pkts;
}

function renderFooter(){
  var lastTs="";
  S.issues.forEach(function(r){var ls=r.last_seen_at||"";if(ls>lastTs)lastTs=ls});
  $("footer-meta").textContent="Pipeline: "+(lastTs?lastTs.slice(0,16).replace("T"," "):"unknown")+" \u00B7 "+S.sources.length+" sources";
}

/* helpers */
function findIssue(id){for(var i=0;i<S.issues.length;i++){if(S.issues[i].issue_id===id)return S.issues[i]}return null}

function showCode(title,code){
  var ol=document.createElement("div");ol.className="code-overlay";
  ol.onclick=function(e){if(e.target===ol)ol.remove()};
  ol.innerHTML='<div class="code-box"><div class="code-box-hdr"><span>'+esc(title)+'</span><div><button class="btn" onclick="App._copyCode()">Copy</button> <button class="btn" onclick="this.closest(\'.code-overlay\').remove()">Close</button></div></div><pre id="code-content">'+esc(code)+'</pre></div>';
  document.body.appendChild(ol);
  showCode._last=code;
}

/* action implementations */
function copyChecklist(id){
  var r=findIssue(id);if(!r)return;
  var lines=["ACTION CHECKLIST: "+r.issue_id,""];
  var lowFric=[],highFric=[];
  (r.actions||[]).forEach(function(a){
    var inf=r.inferred_facts||{};
    var f=inf.friction_level||(a==="notify"||a==="ingest"?"low":"medium");
    if(f==="low")lowFric.push(a);else highFric.push(a);
  });
  if(lowFric.length){lines.push("IMMEDIATE SAFE ACTIONS:");lowFric.forEach(function(a){lines.push("  [ ] "+a)});lines.push("")}
  if(highFric.length){lines.push("ACTIONS REQUIRING BIOMED:");highFric.forEach(function(a){lines.push("  [ ] "+a)});lines.push("")}
  (r.source_mitigations||[]).forEach(function(m){lines.push("  [ ] "+m.action+" ("+m.source+")")});
  if((r.extracted_facts||{}).rationale){lines.push("");lines.push("VALIDATION STEPS:");lines.push("  "+r.extracted_facts.rationale)}
  if((r.non_applicability||[]).length){lines.push("");lines.push("KEY ASSUMPTIONS:");r.non_applicability.forEach(function(n){lines.push("  - "+n)})}
  var unknowns=(r.unknowns||[]).concat(r.evidence_gaps||[]);
  if(unknowns.length){lines.push("");lines.push("KNOWN UNKNOWNS:");unknowns.forEach(function(u){lines.push("  - "+u)})}
  if((r.handling_warnings||[]).length){lines.push("");lines.push("HANDLING WARNINGS:");r.handling_warnings.forEach(function(w){lines.push("  ! "+w)})}
  lines.push("");lines.push("DISCLAIMER: AI-assisted guidance based on approved mitigation patterns. Verify against vendor documentation before implementation.");
  copyText(lines.join("\n"));
  /* flash button */
  var btn=document.querySelector('.btn-primary');if(btn){var orig=btn.textContent;btn.textContent="Copied!";setTimeout(function(){btn.textContent=orig},2000)}
}

function exportJSON(id){var r=findIssue(id);if(!r)return;downloadFile(id+"_packet.json",JSON.stringify(r,null,2),"application/json")}

function exportMD(id){
  var r=findIssue(id);if(!r)return;
  var md="# "+(r.priority||"")+" "+(r.issue_id||"")+"\n\n**"+(r.title||"")+"**\n\n"+(r.summary||"")+"\n\n";
  if((r.source_mitigations||[]).length){md+="## Source mitigations\n\n";r.source_mitigations.forEach(function(m){md+="- **"+m.source+"** (Tier "+(m.source_tier||"?")+"): "+m.action+"\n"});md+="\n"}
  if((r.actions||[]).length){md+="## Recommended actions\n\n";r.actions.forEach(function(a){md+="- [ ] "+a+"\n"});md+="\n"}
  if((r.iocs||[]).length){md+="## IOCs\n\n| Type | Value | Source |\n|------|-------|--------|\n";r.iocs.forEach(function(i){md+="| "+i.type+" | `"+i.value+"` | "+i.source+" |\n"})}
  downloadFile(id+"_packet.md",md,"text/markdown");
}

function genSigma(id){
  var r=findIssue(id);if(!r)return;
  var iocs=r.iocs||[];
  var cves=iocs.filter(function(i){return i.type==="cve"}).map(function(i){return i.value});
  var ips=iocs.filter(function(i){return i.type==="ip"}).map(function(i){return i.value});
  var hashes=iocs.filter(function(i){return i.type==="hash"}).map(function(i){return i.value});
  var domains=iocs.filter(function(i){return i.type==="domain"}).map(function(i){return i.value});
  var rule="title: 'AdvisoryOps: "+r.issue_id+"'\nstatus: experimental\ndescription: "+(r.summary||"").slice(0,200)+"\nreferences:\n  - "+(r.canonical_link||"")+"\nlogsource:\n  product: windows\n  category: process_creation\ndetection:\n  selection:\n";
  if(domains.length)rule+="    DestinationHostname|contains:\n"+domains.map(function(d){return"      - '"+d+"'"}).join("\n")+"\n";
  if(ips.length)rule+="    DestinationIp:\n"+ips.map(function(ip){return"      - '"+ip+"'"}).join("\n")+"\n";
  if(hashes.length)rule+="    Hashes|contains:\n"+hashes.map(function(h){return"      - '"+h+"'"}).join("\n")+"\n";
  if(!domains.length&&!ips.length&&!hashes.length&&cves.length)rule+="    # CVE-based - customize for your environment\n    CommandLine|contains:\n"+cves.map(function(c){return"      - '"+c+"'"}).join("\n")+"\n";
  rule+="  condition: selection\nlevel: high\ntags:\n  - attack.initial_access\n";
  showCode("Sigma rule: "+r.issue_id,rule);
}

function genSuricata(id){
  var r=findIssue(id);if(!r)return;
  var iocs=r.iocs||[];
  var ips=iocs.filter(function(i){return i.type==="ip"}).map(function(i){return i.value});
  var domains=iocs.filter(function(i){return i.type==="domain"}).map(function(i){return i.value});
  var sid=9000000+Math.abs(hashCode(r.issue_id||""));
  var rules=[];
  ips.forEach(function(ip,idx){rules.push('alert ip '+ip+' any -> $HOME_NET any (msg:"AdvisoryOps '+r.issue_id+'"; reference:cve,'+(r.cves||[])[0]+'; sid:'+(sid+idx)+'; rev:1;)')});
  domains.forEach(function(d,idx){rules.push('alert dns any any -> any any (msg:"AdvisoryOps '+r.issue_id+' domain"; dns.query; content:"'+d+'"; sid:'+(sid+100+idx)+'; rev:1;)')});
  if(!rules.length)rules.push("# No network IOCs available for Suricata rule generation\n# CVE: "+(r.cves||[]).join(", "));
  showCode("Suricata rules: "+r.issue_id,rules.join("\n"));
}

function hashCode(s){var h=0;for(var i=0;i<s.length;i++)h=((h<<5)-h+s.charCodeAt(i))|0;return h}

function copyIocsCsv(id){
  var r=findIssue(id);if(!r)return;
  var lines=["type,value,source"];
  (r.iocs||[]).forEach(function(i){lines.push(i.type+","+i.value+","+(i.source||""))});
  copyText(lines.join("\n"));
}

function copyIocsStix(id){
  var r=findIssue(id);if(!r)return;
  var objects=(r.iocs||[]).map(function(ioc,idx){
    var type=ioc.type||"unknown";
    var stixType=type==="ip"?"ipv4-addr":type==="domain"?"domain-name":type==="hash"?"file":type==="url"?"url":"indicator";
    var obj={type:stixType,id:stixType+"--"+idx,spec_version:"2.1"};
    if(stixType==="ipv4-addr")obj.value=ioc.value;
    else if(stixType==="domain-name")obj.value=ioc.value;
    else if(stixType==="url")obj.value=ioc.value;
    else if(stixType==="file")obj.hashes={"SHA-256":ioc.value};
    else{obj.pattern="[indicator:value = '"+ioc.value+"']";obj.pattern_type="stix"}
    return obj;
  });
  downloadFile(r.issue_id+"_iocs.stix.json",JSON.stringify({type:"bundle",id:"bundle--"+r.issue_id,objects:objects},null,2),"application/json");
}

function genAcl(id){
  var r=findIssue(id);if(!r)return;
  var iocs=r.iocs||[];
  var ips=iocs.filter(function(i){return i.type==="ip"}).map(function(i){return i.value});
  var domains=iocs.filter(function(i){return i.type==="domain"}).map(function(i){return i.value});
  var lines=["# ACL rules for "+r.issue_id,"# Review before applying"];
  ips.forEach(function(ip){lines.push("deny ip host "+ip+" any")});
  domains.forEach(function(d){lines.push("# Block domain: "+d)});
  if(!ips.length&&!domains.length)lines.push("# No network IOCs available");
  showCode("ACL rules: "+r.issue_id,lines.join("\n"));
}

function viewLinks(id){
  var r=findIssue(id);if(!r)return;
  var links=[];
  if(r.canonical_link)links.push(r.canonical_link);
  (r.source_mitigations||[]).forEach(function(m){if(m.url&&links.indexOf(m.url)===-1)links.push(m.url)});
  if(links.length){var w=window.open("","_blank");w.document.write("<pre>"+links.join("\n")+"</pre>")}
  else showToast("No source links available");
}

function viewRaw(id){
  var r=findIssue(id);if(!r)return;
  showCode("Raw advisory: "+r.issue_id,r.summary||"No summary available.");
}

function toggleFb(id_safe){
  var el=document.getElementById("fb_"+id_safe.replace(/[^a-z0-9]/gi,"_"));
  if(el)el.classList.toggle("open");
}

function submitFeedback(id,feedbackType){
  try{
    var entry={issue_id:id,feedback_type:feedbackType,timestamp:new Date().toISOString()};
    localStorage.setItem("ao_feedback_"+id,JSON.stringify(entry));
    var all=[];try{var raw=localStorage.getItem("ao_feedback_all");if(raw)all=JSON.parse(raw)}catch(e){}
    all.push(entry);
    try{localStorage.setItem("ao_feedback_all",JSON.stringify(all))}catch(e){}
    showToast("Feedback recorded: "+feedbackType.replace(/_/g," "));
    renderTable();
  }catch(e){showToast("Could not save feedback")}
}

function reportIncorrect(id){
  try{
    localStorage.setItem("ao_report_"+id,JSON.stringify({issue_id:id,feedback_type:"incorrect",timestamp:new Date().toISOString()}));
    showToast("Report recorded");
  }catch(e){showToast("Could not save report")}
}

/* public API */
window.App={
  onSearch:function(v){S.search=v;S.expanded=null;renderTable()},
  toggleFilter:function(i){
    var p=PILL_DEFS[i];if(!p)return;
    if(p.key==="priority")S.filters.priority=S.filters.priority===p.val?"":p.val;
    else S.filters[p.key]=!S.filters[p.key];
    S.expanded=null;renderPills();renderTable();
  },
  setSort:function(col){if(S.sortCol===col)S.sortDir*=-1;else{S.sortCol=col;S.sortDir=col==="issue_id"||col==="title"?1:-1}renderTable()},
  toggle:function(id){S.expanded=S.expanded===id?null:id;renderTable()},
  sortSrc:function(col){if(S.srcSortCol===col)S.srcSortDir*=-1;else{S.srcSortCol=col;S.srcSortDir=1}renderSources()},
  copyChecklist:copyChecklist,exportJSON:exportJSON,exportMD:exportMD,
  genSigma:genSigma,genSuricata:genSuricata,
  copyIocsCsv:copyIocsCsv,copyIocsStix:copyIocsStix,genAcl:genAcl,
  viewLinks:viewLinks,viewRaw:viewRaw,
  toggleFb:toggleFb,submitFeedback:submitFeedback,reportIncorrect:reportIncorrect,
  _copyCode:function(){if(showCode._last)copyText(showCode._last)}
};
})();
</script>
</body>
</html>'''


def build_community_feed(
    *,
    set_id: str = "gold_pass1",
    refresh: bool = False,
    refresh_limit: int = 10,
    out_root_discover: str = "outputs/discover",
    out_root_runs: str = "outputs/source_runs",
    out_root_community: str = "outputs/community_public",
    only_new: bool = False,
    limit_per_source: int = 200,
    limit_issues: int = 0,
    min_priority: str = "P2",
    top: int = 100,
    latest: int = 0,
    recommend: bool = False,
    recommend_model: str = "gpt-4o-mini",
    recommend_priorities: Sequence[str] = ("P0", "P1"),
    ai_score: bool = False,
    ai_score_model: str = "gpt-4o-mini",
    summarize: bool = False,
    summarize_model: str = "gpt-4o-mini",
    summarize_priorities: Sequence[str] = ("P0", "P1", "P2"),
    extract_mitigations: bool = False,
    extract_mitigations_model: str = "gpt-4o-mini",
    extract_mitigations_priorities: Sequence[str] = ("P0", "P1", "P2"),
    enrich_pages: bool = False,
    enrich_pages_priorities: Sequence[str] = ("P0", "P1", "P2"),
    backfill: bool = True,
    _recommend_call_fn: Optional[Callable] = None,
    _ai_classify_fn: Optional[Callable] = None,
    _summarize_call_fn: Optional[Callable] = None,
    _extract_mitigations_call_fn: Optional[Callable] = None,
    _nvd_fetch_fn: Optional[Callable] = None,
    _backfill_fetch_fns: Optional[Dict[str, Callable]] = None,
) -> Tuple[Path, Path, Path]:
    if latest < 0:
        raise ValueError("--latest must be >= 0")

    # --- Backfill incremental updates (before discover/correlate) ---
    if backfill:
        from .sources.backfill_registry import run_all_incremental

        print("")
        print("Running backfill incremental updates...")
        backfill_results = run_all_incremental(
            out_root=out_root_discover,
            _fetch_fns=_backfill_fetch_fns,
        )
        print(
            f"  Backfill: {backfill_results['modules_run']} run, "
            f"{backfill_results['modules_skipped']} skipped, "
            f"{backfill_results['modules_failed']} failed"
        )
        for src_id, detail in backfill_results.get("details", {}).items():
            status = detail.get("status", "unknown")
            if status == "error":
                print(f"  WARNING: {src_id} failed: {detail.get('error', '?')}")
            elif status == "completed":
                new_sigs = detail.get("new_signals_published", 0)
                total_sigs = detail.get("total_signals_published", 0)
                print(f"  {src_id}: {total_sigs} signals ({new_sigs} new)")

    manifest = load_community_manifest()
    selected_set = manifest.get_set(set_id)
    cfg = load_sources_config()
    cfg_by_id = {s.source_id: s for s in cfg.sources}

    if refresh:
        for source_id in selected_set.source_ids:
            print("")
            print(f"Refreshing source: {source_id}")
            source_run(
                source_id,
                limit=refresh_limit,
                ingest=False,
                dry_run=False,
                ingest_mode="new",
                out_root_discover=out_root_discover,
                out_root_runs=out_root_runs,
                show_links=False,
                reset_state=False,
            )

    community_root = Path(out_root_community)
    community_root.mkdir(parents=True, exist_ok=True)

    correlate_root = community_root / "correlate"
    scored_root = community_root / "scored"

    issues_path, _ = correlate(
        out_root_discover=out_root_discover,
        out_root_issues=str(correlate_root),
        sources=selected_set.source_ids,
        only_new=only_new,
        limit_per_source=limit_per_source,
        limit_issues=limit_issues,
        dry_run=False,
    )
    if issues_path is None:
        raise RuntimeError("Correlate did not produce issues output")

    _, alerts_path, _ = score_issues(
        in_issues=str(issues_path),
        out_root_scored=str(scored_root),
        min_priority=min_priority,
        top=top,
        ai_score=ai_score,
        ai_score_model=ai_score_model,
        _ai_classify_fn=_ai_classify_fn,
    )

    scored_rows = _read_jsonl(scored_root / "issues_scored.jsonl")
    alert_rows = _read_jsonl(alerts_path)

    # --- Run contradiction detector on issues with 2+ sources ---
    from .contradiction_detector import detect_contradictions

    scored_rows = detect_contradictions(scored_rows)
    # Also annotate alert_rows (they're a subset of scored_rows by issue_id)
    consensus_by_id = {r["issue_id"]: r.get("source_consensus", {}) for r in scored_rows}
    for ar in alert_rows:
        iid = ar.get("issue_id", "")
        if iid in consensus_by_id:
            ar["source_consensus"] = consensus_by_id[iid]

    # --- Extract KEV fields from signals into issue-level fields ---
    from .nvd_enrich import (
        enrich_issues as nvd_enrich_issues,
        deduplicate_summary,
        generate_remediation_steps,
    )

    _KEV_SOURCES = {"cisa-kev-json", "cisa-kev-csv"}
    _KEV_FIELDS = ("kev_required_action", "kev_due_date", "kev_vendor", "kev_product")
    kev_enriched = 0
    for issue in scored_rows:
        signals = issue.get("signals") or []
        for sig in signals:
            if sig.get("source", "") not in _KEV_SOURCES:
                continue
            for field in _KEV_FIELDS:
                val = sig.get(field, "")
                if val and not issue.get(field):
                    issue[field] = val
        # Populate vendor/severity from KEV if still empty
        if not issue.get("vendor") and issue.get("kev_vendor"):
            issue["vendor"] = issue["kev_vendor"]
        if issue.get("kev_vendor") or issue.get("kev_required_action"):
            kev_enriched += 1
    if kev_enriched:
        print(f"\n  KEV fields: enriched {kev_enriched} issues with KEV-specific data")

    # --- NVD enrichment (deterministic — cached, no AI) ---
    nvd_count = nvd_enrich_issues(scored_rows, _fetch_fn=_nvd_fetch_fn)
    print(f"\n  NVD enrichment: enriched {nvd_count}/{len(scored_rows)} issues with CVSS/CWE/CPE data")

    # --- Cross-reference enrichment (EPSS, CWE names) ---
    try:
        from .enrichment.cross_reference import apply_enrichments
        xref_counts = apply_enrichments(scored_rows, epss=True, cwe=True, vulnrichment=False)
        xref_parts = [f"{k}={v}" for k, v in xref_counts.items() if v]
        if xref_parts:
            print(f"  Cross-reference enrichment: {', '.join(xref_parts)}")
    except Exception as exc:
        import logging as _logging
        _logging.getLogger(__name__).warning("Cross-reference enrichment failed: %s", exc)

    # Backfill severity from CVSS if the scorer left it empty
    for issue in scored_rows:
        if not issue.get("severity") and issue.get("cvss_severity"):
            issue["severity"] = issue["cvss_severity"].lower()

    # --- Summary deduplication ---
    dedup_count = 0
    for issue in scored_rows:
        old_summary = issue.get("summary", "")
        deduplicate_summary(issue)
        if issue.get("summary") != old_summary:
            dedup_count += 1
    if dedup_count:
        print(f"  Summary dedup: {dedup_count} issues got per-CVE descriptions")

    # Propagate KEV/NVD fields to alert_rows
    enriched_by_id = {r["issue_id"]: r for r in scored_rows}
    _NVD_KEV_FIELDS = (
        "kev_required_action", "kev_due_date", "kev_vendor", "kev_product",
        "nvd_description", "cvss_score", "cvss_severity", "cvss_vector",
        "cwe_ids", "affected_products", "source_summary", "vendor", "severity",
    )
    for ar in alert_rows:
        iid = ar.get("issue_id", "")
        src = enriched_by_id.get(iid)
        if src:
            for field in _NVD_KEV_FIELDS:
                if src.get(field) and not ar.get(field):
                    ar[field] = src[field]
            # Summary should match
            ar["summary"] = src.get("summary", ar.get("summary", ""))

    # --- Optional AI summarization pass ---
    summarize_count = 0
    if summarize:
        from .summarize import summarize_advisory

        priority_set_s = set(summarize_priorities)
        targets = [r for r in scored_rows if r.get("priority") in priority_set_s]
        print(f"\n  Summarize: rewriting summaries for {len(targets)} issues "
              f"(priorities: {', '.join(sorted(priority_set_s))})")

        scored_by_id = {r["issue_id"]: r for r in scored_rows}
        alert_by_id = {r["issue_id"]: r for r in alert_rows}

        for issue in targets:
            issue_id = issue.get("issue_id", "unknown")
            try:
                result = summarize_advisory(
                    issue,
                    model=summarize_model,
                    _call_fn=_summarize_call_fn,
                )
                summarize_count += 1
                cached_label = " (cached)" if result.get("from_cache") else ""

                # Merge results back into scored_rows and alert_rows
                for row_dict in (scored_by_id, alert_by_id):
                    row = row_dict.get(issue_id)
                    if row is None:
                        continue
                    if result["summary"]:
                        row["summary"] = result["summary"]
                    # Merge unknowns (deduplicate)
                    existing_u = set(row.get("unknowns") or [])
                    for u in result.get("unknowns", []):
                        if u not in existing_u:
                            row.setdefault("unknowns", []).append(u)
                            existing_u.add(u)
                    # Merge handling_warnings (deduplicate)
                    existing_hw = set(row.get("handling_warnings") or [])
                    for w in result.get("handling_warnings", []):
                        if w not in existing_hw:
                            row.setdefault("handling_warnings", []).append(w)
                            existing_hw.add(w)
                    row["evidence_completeness"] = result.get("evidence_completeness", 0.0)
                    row["generated_by"] = "ai"

                if summarize_count <= 3 or summarize_count % 50 == 0:
                    print(f"    Summarized: {issue_id}{cached_label}")
            except Exception as exc:
                print(f"    Warning: summarize failed for {issue_id}: {exc}")

        print(f"  Summarize: {summarize_count}/{len(targets)} issues rewritten")

    # --- Optional page enrichment pass (fetch advisory pages for richer text) ---
    pages_fetched = 0
    pages_failed = 0
    if enrich_pages:
        from .page_enrich import enrich_issue_from_links

        priority_set_e = set(enrich_pages_priorities)
        enrich_targets = [r for r in scored_rows if r.get("priority") in priority_set_e]
        print(f"\n  Page enrichment: fetching pages for {len(enrich_targets)} issues "
              f"(priorities: {', '.join(sorted(priority_set_e))})")

        for issue in enrich_targets:
            try:
                enriched = enrich_issue_from_links(issue)
                if enriched:
                    issue["enriched_text"] = enriched
                    pages_fetched += 1
                else:
                    pages_failed += 1
            except Exception as exc:
                pages_failed += 1
                print(f"    Warning: page fetch failed for {issue.get('issue_id', '?')}: {exc}")

        print(f"  Page enrichment: {pages_fetched} fetched, {pages_failed} failed/empty")

    # --- IOC extraction (deterministic — runs on ALL issues) ---
    from .ioc_extract import extract_iocs

    ioc_total = 0
    for issue in scored_rows:
        iocs = extract_iocs(issue)
        issue["iocs"] = iocs
        ioc_total += len(iocs)
    # Propagate to alert_rows
    ioc_by_id = {r["issue_id"]: r.get("iocs", []) for r in scored_rows}
    for ar in alert_rows:
        ar["iocs"] = ioc_by_id.get(ar.get("issue_id", ""), [])
    print(f"\n  IOCs: extracted {ioc_total} indicators from {len(scored_rows)} issues")

    # --- Optional source mitigation extraction pass ---
    mitigation_count = 0
    if extract_mitigations:
        from .source_mitigations import extract_source_mitigations

        priority_set_m = set(extract_mitigations_priorities)
        mit_targets = [r for r in scored_rows if r.get("priority") in priority_set_m]
        print(f"\n  Source mitigations: extracting from {len(mit_targets)} issues "
              f"(priorities: {', '.join(sorted(priority_set_m))})")

        alert_by_id_m = {r["issue_id"]: r for r in alert_rows}

        for issue in mit_targets:
            issue_id = issue.get("issue_id", "unknown")
            try:
                mits = extract_source_mitigations(
                    issue,
                    model=extract_mitigations_model,
                    _call_fn=_extract_mitigations_call_fn,
                )
                issue["source_mitigations"] = mits
                mitigation_count += len(mits)

                # Propagate to alert_rows
                if issue_id in alert_by_id_m:
                    alert_by_id_m[issue_id]["source_mitigations"] = mits

                if len([r for r in scored_rows if r.get("source_mitigations")]) <= 3:
                    print(f"    Extracted {len(mits)} mitigations: {issue_id}")
            except Exception as exc:
                print(f"    Warning: mitigation extraction failed for {issue_id}: {exc}")

        mit_issues_direct = sum(1 for r in scored_rows if r.get("source_mitigations"))
        print(f"  Source mitigations: {mitigation_count} mitigations from {mit_issues_direct} issues")

        # --- Cross-source CVE correlation (deterministic) ---
        from .source_mitigations import correlate_mitigations_by_cve

        cross_count = correlate_mitigations_by_cve(
            [r for r in scored_rows if r.get("priority") in priority_set_m]
        )
        if cross_count:
            # Propagate cross-source mitigations to alert_rows
            for r in scored_rows:
                iid = r.get("issue_id", "")
                if iid in alert_by_id_m and r.get("source_mitigations"):
                    alert_by_id_m[iid]["source_mitigations"] = r["source_mitigations"]
            print(f"  Cross-source correlation: {cross_count} additional issues gained mitigations")

        mit_issues_total = sum(
            1 for r in scored_rows
            if r.get("priority") in priority_set_m and r.get("source_mitigations")
        )
        print(f"  Total issues with source mitigations: {mit_issues_total}/{len(mit_targets)}")

    # --- Generate human-readable remediation steps ---
    remediation_count = 0
    for issue in scored_rows:
        steps = generate_remediation_steps(issue)
        if steps:
            issue["remediation_steps"] = steps
            remediation_count += 1
    # Propagate to alert_rows
    remediation_by_id = {r["issue_id"]: r.get("remediation_steps", []) for r in scored_rows}
    for ar in alert_rows:
        iid = ar.get("issue_id", "")
        if iid in remediation_by_id:
            ar["remediation_steps"] = remediation_by_id[iid]
    print(f"\n  Remediation: generated human-readable steps for {remediation_count} issues")

    # --- FDA risk class enrichment ---
    from .enrichment.fda_classification import (
        extract_risk_class_from_recall,
        lookup_risk_class,
        fetch_classification_database,
    )
    from .score import _score_fda_risk_class, _priority_from_score, _actions_for_priority

    _OPENFDA_SOURCES = {"openfda-device-recalls", "openfda-recalls-historical"}
    _FDA_ENFORCEMENT_SOURCES = {"fda-safety-comms-historical"}
    _ALL_FDA_SOURCES = _OPENFDA_SOURCES | _FDA_ENFORCEMENT_SOURCES
    openfda_cache_dir = Path("outputs/openfda_cache")
    fda_rc_count = 0
    fda_rc_lookup_count = 0

    def _apply_fda_score_bonus(issue: Dict[str, Any]) -> None:
        """Inline-update score/why/priority after setting fda_risk_class and enriching title.

        Two responsibilities:
        1. Apply the FDA risk class bonus (+30/+10/+0).
        2. Re-scan the (now-enriched) title/summary for device, clinical, and
           patch signals that the original scoring missed because the text was
           thin at scoring time. Only adds bonuses not already present.
        """
        from .score import (
            _DEVICE_SIGNALS, _CLINICAL_SIGNALS, _PATCH_SIGNALS,
        )

        issue_why = issue.get("why") or []
        issue_why = [w for w in issue_why if not w.startswith("priority:")]
        added_pts = 0

        # 1. FDA risk class bonus
        fda_pts, fda_why_strs = _score_fda_risk_class(issue)
        if fda_pts:
            added_pts += fda_pts
            issue_why.extend(fda_why_strs)

        # 2. Re-scan enriched text for device/clinical/patch signals not already awarded
        text = f"{issue.get('issue_id', '')}\n{issue.get('title', '')}\n{issue.get('summary', '')}"
        existing_labels = set(issue_why)

        for signal_list in (_DEVICE_SIGNALS, _CLINICAL_SIGNALS, _PATCH_SIGNALS):
            for rx, pts, label in signal_list:
                if label in existing_labels:
                    continue  # Already awarded in original scoring
                if rx.search(text):
                    added_pts += pts
                    issue_why.append(label)
                    existing_labels.add(label)

        if added_pts == 0 and fda_pts == 0:
            return

        issue["score"] = issue.get("score", 0) + added_pts
        new_priority = _priority_from_score(issue["score"])
        issue_why.append(f"priority: {new_priority} (score={issue['score']})")
        issue["why"] = issue_why
        issue["priority"] = new_priority
        issue["actions"] = _actions_for_priority(new_priority)

    # Load classification database lazily (only if needed for secondary lookups)
    _classifications_db: Optional[Dict[str, Any]] = None

    # Device-like keywords to gate secondary lookup
    import re as _re
    _DEVICE_GATE_RE = _re.compile(
        r"medical device|infusion pump|ventilator|pacemaker|defibrillator|implant"
        r"|monitor|imaging|dicom|pacs|catheter|surgical|diagnostic|therapeutic"
        r"|x-ray|ultrasound|mri|ct scan|insulin|oxygenator|respirator"
        r"|fda|recall|class\s+[iI]{1,3}\b",
        _re.IGNORECASE,
    )

    def _enrich_issue_from_recall(issue: Dict[str, Any], recall_data: dict) -> None:
        """Enrich issue title and summary from recall record fields.

        Existing issue titles from cached signals may be thin (e.g. just
        "30666: Philips Medical Systems"). The recall record has richer
        fields (openfda.device_name, product_description, reason_for_recall)
        that provide clinical keywords for scoring.
        """
        openfda = recall_data.get("openfda") or {}
        device_name = str(openfda.get("device_name", "") or "").strip()
        product_desc = str(recall_data.get("product_description", "") or "").strip()
        reason = str(recall_data.get("reason_for_recall", "") or "").strip()
        firm = str(recall_data.get("recalling_firm", "") or "").strip()

        # Enrich title if it's thin (just recall number + firm)
        current_title = issue.get("title", "")
        title_device = device_name or product_desc[:120]
        if title_device and title_device not in current_title:
            if firm:
                issue["title"] = f"{title_device} recall ({firm})"
            else:
                issue["title"] = f"{title_device} recall"

        # Enrich summary with device name and reason
        current_summary = issue.get("summary", "")
        enrichment_parts = []
        if device_name and device_name not in current_summary:
            enrichment_parts.append(f"Device: {device_name}.")
        if product_desc and product_desc not in current_summary and product_desc not in (device_name or ""):
            enrichment_parts.append(product_desc)
        if reason and reason not in current_summary:
            enrichment_parts.append(f"Reason: {reason}")
        if enrichment_parts:
            enrichment = " | ".join(enrichment_parts)
            if current_summary:
                issue["summary"] = f"{current_summary} | {enrichment}"
            else:
                issue["summary"] = enrichment

    fda_titles_enriched = 0

    for issue in scored_rows:
        if issue.get("fda_risk_class"):
            continue

        sources = issue.get("sources") or []
        signals = issue.get("signals") or []

        # Primary: extract from cached recall record
        if any(s in _OPENFDA_SOURCES for s in sources):
            for sig in signals:
                if sig.get("source", "") not in _OPENFDA_SOURCES:
                    continue
                guid = sig.get("guid", "")
                if not guid:
                    continue
                recall_file = openfda_cache_dir / f"recall_{guid}.json"
                if not recall_file.exists():
                    continue
                try:
                    recall_data = json.loads(recall_file.read_text(encoding="utf-8"))
                    rc = extract_risk_class_from_recall(recall_data)
                    if rc:
                        issue["fda_risk_class"] = rc
                        _enrich_issue_from_recall(issue, recall_data)
                        _apply_fda_score_bonus(issue)
                        fda_rc_count += 1
                        fda_titles_enriched += 1
                        break
                except Exception:
                    continue

        # Secondary: classification database lookup (only for device-like issues)
        if not issue.get("fda_risk_class"):
            text = f"{issue.get('title', '')} {issue.get('summary', '')}"
            if _DEVICE_GATE_RE.search(text):
                if _classifications_db is None:
                    try:
                        _classifications_db = fetch_classification_database()
                    except Exception as exc:
                        import logging as _log
                        _log.getLogger(__name__).warning(
                            "Failed to load classification database: %s", exc
                        )
                        _classifications_db = {}

                # Try product_code from signals first
                product_code = None
                for sig in signals:
                    if sig.get("source", "") in _OPENFDA_SOURCES:
                        guid = sig.get("guid", "")
                        recall_file = openfda_cache_dir / f"recall_{guid}.json"
                        if recall_file.exists():
                            try:
                                rd = json.loads(recall_file.read_text(encoding="utf-8"))
                                product_code = rd.get("product_code")
                            except Exception:
                                pass

                device_name = issue.get("title", "")
                rc = lookup_risk_class(
                    product_code=product_code,
                    device_name=device_name,
                    classifications=_classifications_db,
                )
                if rc:
                    issue["fda_risk_class"] = rc
                    _apply_fda_score_bonus(issue)
                    fda_rc_lookup_count += 1

    # Propagate FDA fields + updated score/why/priority to alert_rows
    fda_enriched_by_id = {
        r["issue_id"]: r for r in scored_rows if r.get("fda_risk_class")
    }
    _FDA_PROPAGATE_FIELDS = ("fda_risk_class", "score", "priority", "actions", "why")
    for ar in alert_rows:
        iid = ar.get("issue_id", "")
        src = fda_enriched_by_id.get(iid)
        if src:
            for fld in _FDA_PROPAGATE_FIELDS:
                if src.get(fld) is not None:
                    ar[fld] = src[fld]

    fda_total = fda_rc_count + fda_rc_lookup_count
    print(f"\n  FDA risk class: {fda_total} issues enriched "
          f"({fda_rc_count} from recalls, {fda_rc_lookup_count} from classification DB)")

    # --- Healthcare relevance tagging + category classification ---
    from .healthcare_filter import is_healthcare_relevant, classify_healthcare_category

    hc_count = 0
    hc_categories: Dict[str, int] = {}
    for issue in scored_rows:
        relevant = is_healthcare_relevant(issue)
        issue["healthcare_relevant"] = relevant
        if relevant:
            hc_count += 1
            cat = classify_healthcare_category(issue)
            issue["healthcare_category"] = cat
            hc_categories[cat] = hc_categories.get(cat, 0) + 1
    for ar in alert_rows:
        ar["healthcare_relevant"] = is_healthcare_relevant(ar)
        if ar["healthcare_relevant"]:
            ar["healthcare_category"] = classify_healthcare_category(ar)
    print(f"\n  Healthcare relevance: {hc_count}/{len(scored_rows)} issues tagged as healthcare-relevant")
    if hc_categories:
        cats_str = ", ".join(f"{k}={v}" for k, v in sorted(hc_categories.items()))
        print(f"  Healthcare categories: {cats_str}")

    # --- KEV + medical device cross-reference ---
    from .score import _score_kev_medical_device

    _KEV_SOURCE_INDICATORS = {"cisa-kev-json", "cisa-kev-csv"}
    kev_med_count = 0
    for issue in scored_rows:
        if not issue.get("healthcare_relevant"):
            continue
        # Check KEV indicators
        has_kev = bool(issue.get("kev_due_date")) or bool(issue.get("kev_required_action"))
        if not has_kev:
            sources = issue.get("sources") or []
            has_kev = any("kev" in s.lower() for s in sources)
        if has_kev:
            issue["is_kev_medical_device"] = True
            # Inline-update score/why/priority
            pts, why_strs = _score_kev_medical_device(issue)
            if pts:
                issue_why = issue.get("why") or []
                issue_why = [w for w in issue_why if not w.startswith("priority:")]
                issue_why.extend(why_strs)
                issue["score"] = issue.get("score", 0) + pts
                new_priority = _priority_from_score(issue["score"])
                issue_why.append(f"priority: {new_priority} (score={issue['score']})")
                issue["why"] = issue_why
                issue["priority"] = new_priority
                issue["actions"] = _actions_for_priority(new_priority)
            kev_med_count += 1

    # Propagate to alert_rows
    kev_med_by_id = {r["issue_id"]: r for r in scored_rows if r.get("is_kev_medical_device")}
    _KEV_MED_FIELDS = ("is_kev_medical_device", "score", "priority", "actions", "why")
    for ar in alert_rows:
        iid = ar.get("issue_id", "")
        src = kev_med_by_id.get(iid)
        if src:
            for fld in _KEV_MED_FIELDS:
                if src.get(fld) is not None:
                    ar[fld] = src[fld]

    print(f"\n  KEV medical device: {kev_med_count} issues flagged as actively exploited medical device vulnerabilities")

    # --- Coverage tracking ---
    p012 = [r for r in scored_rows if r.get("priority") in ("P0", "P1", "P2")]
    if p012:
        has_src_mits = sum(1 for r in p012 if r.get("source_mitigations"))
        has_actions = sum(1 for r in p012 if r.get("actions"))
        has_any = sum(1 for r in p012 if r.get("source_mitigations") or r.get("actions"))
        has_none = len(p012) - has_any
        print(f"\n  --- P0-P2 guidance coverage ({len(p012)} issues) ---")
        print(f"    Source-cited mitigations: {has_src_mits} ({has_src_mits*100//len(p012)}%)")
        print(f"    Playbook recommendations: {has_actions} ({has_actions*100//len(p012)}%)")
        print(f"    ANY guidance:             {has_any} ({has_any*100//len(p012)}%)")
        print(f"    NO guidance:              {has_none} ({has_none*100//len(p012)}%)")

    feed_rows = _sort_feed_entries([_feed_entry(r) for r in scored_rows])
    latest_rows = feed_rows[:latest] if latest > 0 else feed_rows
    alert_feed_rows = _sort_feed_entries([_feed_entry(r) for r in alert_rows])

    # --- Optional recommendation pass ---
    packets_dir: Optional[Path] = None
    packet_count = 0

    # Collect recommendation trust data to merge back into feed entries
    packet_trust_by_id: Dict[str, Dict[str, Any]] = {}

    if recommend:
        from .playbook import load_playbook
        from .recommend import recommend_mitigations
        from .packet_export import export_json, _safe_stem

        pb = load_playbook()
        packets_dir = community_root / "packets"
        packets_dir.mkdir(parents=True, exist_ok=True)

        priority_set = set(recommend_priorities)
        target_issues = [r for r in alert_rows if r.get("priority") in priority_set]
        print(f"\n  Recommend: generating packets for {len(target_issues)} alerts "
              f"(priorities: {', '.join(sorted(priority_set))})")

        for issue in target_issues:
            issue_id = issue.get("issue_id", "unknown")
            try:
                packet = recommend_mitigations(
                    issue,
                    pb,
                    model=recommend_model,
                    _call_fn=_recommend_call_fn,
                )
                stem = _safe_stem(issue_id)
                export_json(packet, packets_dir / f"{stem}_packet.json")
                packet_count += 1
                cached_label = " (cached)" if packet.from_cache else ""
                print(f"    Wrote packet: {issue_id}{cached_label}")

                # Collect trust fields from recommendation for merge-back
                packet_trust_by_id[issue_id] = {
                    "handling_warnings": packet.handling_warnings or [],
                    "evidence_gaps": packet.evidence_gaps or [],
                    "extracted_facts": packet.extracted_facts or {},
                    "inferred_facts": packet.inferred_facts or {},
                    "confidence_by_field": packet.confidence_by_field or {},
                    "evidence_sources": packet.evidence_sources or [],
                    "reasoning": packet.reasoning or "",
                    "non_applicability": packet.non_applicability or [],
                    "generated_by": "ai",
                }
            except Exception as exc:
                print(f"    Warning: recommend failed for {issue_id}: {exc}")

        print(f"  Recommend: {packet_count}/{len(target_issues)} packets written")

    # --- Merge recommendation trust data back into feed rows ---
    if packet_trust_by_id:
        def _merge_trust(rows: List[Dict[str, Any]]) -> None:
            for row in rows:
                iid = row.get("issue_id", "")
                if iid not in packet_trust_by_id:
                    continue
                pkt = packet_trust_by_id[iid]
                # Merge list fields (deduplicate)
                for list_field in ("handling_warnings", "evidence_gaps", "non_applicability"):
                    existing = set(row.get(list_field) or [])
                    for v in pkt.get(list_field, []):
                        if v not in existing:
                            row.setdefault(list_field, []).append(v)
                            existing.add(v)
                # evidence_gaps also populate unknowns (what we don't know)
                unknowns_existing = set(row.get("unknowns") or [])
                for v in pkt.get("evidence_gaps", []):
                    if v not in unknowns_existing:
                        row.setdefault("unknowns", []).append(v)
                        unknowns_existing.add(v)
                # Merge/overwrite dict fields (recommendation is more specific)
                for dict_field in ("extracted_facts", "inferred_facts", "confidence_by_field"):
                    existing_d = row.get(dict_field) or {}
                    pkt_d = pkt.get(dict_field) or {}
                    if pkt_d:
                        merged = {**existing_d, **pkt_d}
                        row[dict_field] = merged
                # Merge evidence_sources (deduplicate)
                existing_sources = set(row.get("evidence_sources") or [])
                for s in pkt.get("evidence_sources", []):
                    if s not in existing_sources:
                        row.setdefault("evidence_sources", []).append(s)
                        existing_sources.add(s)
                row["generated_by"] = "ai"

        _merge_trust(feed_rows)
        _merge_trust(alert_feed_rows)
        _merge_trust(latest_rows)

    out_issues_public = community_root / "issues_public.jsonl"
    out_alerts_public = community_root / "alerts_public.jsonl"
    out_latest = community_root / "feed_latest.json"
    out_csv = community_root / "feed.csv"
    out_rss = community_root / "feed.xml"
    out_sources = community_root / "validated_sources.json"
    out_meta = community_root / "meta.json"
    out_dashboard = community_root / "dashboard.html"

    _write_jsonl(out_issues_public, feed_rows)
    _write_jsonl(out_alerts_public, alert_feed_rows)
    out_latest.write_text(json.dumps(latest_rows, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")

    # Healthcare-relevant feed
    out_healthcare = community_root / "feed_healthcare.json"
    healthcare_rows = [r for r in latest_rows if r.get("healthcare_relevant") is True]
    out_healthcare.write_text(json.dumps(healthcare_rows, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    print(f"  Healthcare feed:  {out_healthcare} ({len(healthcare_rows)} issues)")

    # KEV medical device feed
    out_kev_med = community_root / "feed_medical_device_kev.json"
    kev_med_rows = [r for r in latest_rows if r.get("is_kev_medical_device") is True]
    out_kev_med.write_text(json.dumps(kev_med_rows, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    print(f"  KEV medical feed: {out_kev_med} ({len(kev_med_rows)} issues)")

    _write_csv(out_csv, feed_rows)
    _write_rss(out_rss, feed_rows, top=50)

    # Filtered RSS feeds
    _write_rss(
        community_root / "feed_healthcare.xml",
        healthcare_rows, top=100,
        title="AdvisoryOps \u2014 Healthcare Medical Device Advisories",
        description="Healthcare and medical device cybersecurity advisories",
    )
    _write_rss(
        community_root / "feed_kev_medical_device.xml",
        kev_med_rows, top=100,
        title="AdvisoryOps \u2014 Actively Exploited Medical Device Vulnerabilities",
        description="Medical device vulnerabilities in CISA's Known Exploited Vulnerabilities catalog",
    )
    class_3_rows = [r for r in latest_rows if r.get("fda_risk_class") == "3"]
    _write_rss(
        community_root / "feed_class_3.xml",
        class_3_rows, top=100,
        title="AdvisoryOps \u2014 FDA Class III Medical Device Advisories",
        description="Advisories affecting FDA Class III (highest-risk) medical devices",
    )
    p0_p1_rows = [r for r in latest_rows if r.get("priority") in ("P0", "P1")]
    _write_rss(
        community_root / "feed_p0_p1.xml",
        p0_p1_rows, top=100,
        title="AdvisoryOps \u2014 High Priority Advisories",
        description="P0 and P1 priority cybersecurity advisories requiring immediate attention",
    )
    print(f"  RSS feeds:  feed.xml (50), feed_healthcare.xml ({len(healthcare_rows[:100])}), "
          f"feed_kev_medical_device.xml ({len(kev_med_rows[:100])}), "
          f"feed_class_3.xml ({len(class_3_rows[:100])}), feed_p0_p1.xml ({len(p0_p1_rows[:100])})")

    # Excel export (optional — only if openpyxl is available)
    try:
        from .excel_export import export_excel
        out_xlsx = community_root / "issues_public.xlsx"
        export_excel(feed_rows, out_xlsx)
        print(f"  Excel:      {out_xlsx}")
    except ImportError:
        pass  # openpyxl not installed; skip silently

    _generate_dashboard(out_dashboard)

    validated_sources = []
    for source_id in selected_set.source_ids:
        src = cfg_by_id[source_id]
        validated_sources.append(
            {
                "source_id": src.source_id,
                "name": src.name,
                "scope": src.scope,
                "page_type": src.page_type,
                "entry_url": src.entry_url,
                "enabled": src.enabled,
                "status": "validated",
            }
        )
    for source_id in manifest.candidate_sources:
        src = cfg_by_id[source_id]
        validated_sources.append(
            {
                "source_id": src.source_id,
                "name": src.name,
                "scope": src.scope,
                "page_type": src.page_type,
                "entry_url": src.entry_url,
                "enabled": src.enabled,
                "status": "candidate",
            }
        )
    out_sources.write_text(json.dumps(validated_sources, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")

    meta = {
        "set_id": selected_set.set_id,
        "set_name": selected_set.name,
        "description": selected_set.description,
        "out_root_discover": out_root_discover,
        "out_root_runs": out_root_runs,
        "out_root_community": str(community_root),
        "params": {
            "refresh": bool(refresh),
            "refresh_limit": int(refresh_limit),
            "only_new": bool(only_new),
            "limit_per_source": int(limit_per_source),
            "limit_issues": int(limit_issues),
            "min_priority": min_priority,
            "top": int(top),
            "latest": int(latest),
        },
        "counts": {
            "validated_sources": len(selected_set.source_ids),
            "candidate_sources": len(manifest.candidate_sources),
            "issues_public": len(feed_rows),
            "alerts_public": len(alert_feed_rows),
            "latest": len(latest_rows),
            "healthcare": len(healthcare_rows),
            "packets": packet_count,
        },
        "outputs": {
            "issues_public_jsonl": str(out_issues_public),
            "alerts_public_jsonl": str(out_alerts_public),
            "feed_latest_json": str(out_latest),
            "feed_healthcare_json": str(out_healthcare),
            "feed_csv": str(out_csv),
            "feed_rss_xml": str(out_rss),
            "validated_sources_json": str(out_sources),
            "meta_json": str(out_meta),
            "dashboard_html": str(out_dashboard),
            "packets_dir": str(packets_dir) if packets_dir else None,
        },
    }
    out_meta.write_text(json.dumps(meta, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")

    # --- Deploy to docs/ for GitHub Pages ---
    _deploy_docs(out_dashboard, out_latest, out_sources)

    print("")
    print("Community build summary:")
    print(f"  Set:              {selected_set.set_id} ({selected_set.name})")
    print(f"  Validated:        {len(selected_set.source_ids)}")
    print(f"  Candidates:       {len(manifest.candidate_sources)}")
    print(f"  Issues public:    {len(feed_rows)}")
    print(f"  Alerts public:    {len(alert_feed_rows)}")
    print(f"  Latest entries:   {len(latest_rows)}")
    print(f"  Wrote:            {out_issues_public}")
    print(f"  Wrote:            {out_alerts_public}")
    print(f"  Wrote:            {out_latest}")
    print(f"  Wrote:            {out_healthcare}")
    print(f"  Wrote:            {out_csv}")
    print(f"  Wrote:            {out_rss}")
    print(f"  Wrote:            {out_dashboard}")
    print(f"  Wrote:            {out_sources}")
    print(f"  Wrote:            {out_meta}")
    if packets_dir:
        print(f"  Packets dir:      {packets_dir} ({packet_count} packets)")

    return out_issues_public, out_alerts_public, out_meta
