"""Stage 6: end-to-end community feed builder.

Orchestrates the full Discover → Correlate → Score → (Recommend) pipeline for
the validated source set defined in ``configs/community_public_sources.json``
and publishes a ready-to-serve feed directory.

Typical invocation::

    advisoryops community-build --set-id gold_pass1 --out-root-community outputs/community_public

What it does
------------
1. (Optional ``--refresh``) Runs ``source_run`` for each source in the selected
   validated set to pull new items before building.
2. Runs ``correlate`` across all discover outputs for the validated source IDs,
   writing intermediate results to ``<out_root_community>/correlate/``.
3. Runs ``score_issues`` on the correlated issues, writing to
   ``<out_root_community>/scored/``.
4. Builds the public feed artifacts (see outputs below).
5. (Optional ``--recommend``) Generates JSON remediation packets for P0/P1 alerts
   via the ``recommend_mitigations`` engine.

Output artifacts (all under ``out_root_community/``)::

    issues_public.jsonl      — all scored issues (full feed, sorted by score desc)
    alerts_public.jsonl      — high-priority subset (≥ min_priority)
    feed_latest.json         — most recent N issues as a JSON array (for the dashboard)
    feed.csv                 — spreadsheet-friendly export of all issues
    validated_sources.json   — source registry snapshot (validated + candidates)
    meta.json                — build metadata (params, counts, timestamps)
    packets/                 — per-issue JSON remediation packets (if --recommend)

The dashboard (``dashboard.html``) is generated by ``_generate_dashboard()``
and written alongside the other feed artifacts.  It loads feed_latest.json
and alerts_public.jsonl from the same directory via fetch().
"""
from __future__ import annotations

import csv
import json
import xml.etree.ElementTree as ET
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Callable, Dict, Iterable, List, Optional, Sequence, Tuple

from .community_manifest import load_community_manifest
from .correlate import correlate
from .score import score_issues
from .source_run import source_run
from .sources_config import load_sources_config


def _read_jsonl(path: Path) -> List[Dict[str, Any]]:
    rows: List[Dict[str, Any]] = []
    if not path.exists():
        raise FileNotFoundError(f"Missing JSONL file: {path}")
    for line in path.read_text(encoding="utf-8", errors="replace").splitlines():
        line = line.strip()
        if not line:
            continue
        obj = json.loads(line)
        if isinstance(obj, dict):
            rows.append(obj)
    return rows


def _write_jsonl(path: Path, rows: Iterable[Dict[str, Any]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8", newline="\n") as f:
        for row in rows:
            f.write(json.dumps(row, ensure_ascii=False, sort_keys=True) + "\n")


def _feed_entry(issue: Dict[str, Any]) -> Dict[str, Any]:
    entry: Dict[str, Any] = {
        "issue_id": issue.get("issue_id", ""),
        "issue_type": issue.get("issue_type", ""),
        "title": issue.get("title", ""),
        "summary": issue.get("summary", ""),
        "canonical_link": issue.get("canonical_link", ""),
        "cves": issue.get("cves", []) or [],
        "sources": issue.get("sources", []) or [],
        "published_dates": issue.get("published_dates", []) or [],
        "first_seen_at": issue.get("first_seen_at", ""),
        "last_seen_at": issue.get("last_seen_at", ""),
        "score": int(issue.get("score", 0) or 0),
        "priority": issue.get("priority", ""),
        "actions": issue.get("actions", []) or [],
        # Trust layer fields (gracefully default to empty when absent)
        "handling_warnings": issue.get("handling_warnings", []) or [],
        "evidence_gaps": issue.get("evidence_gaps", []) or [],
        "unknowns": issue.get("unknowns", []) or [],
        "source_consensus": issue.get("source_consensus") or {},
        "source_authority_weight": issue.get("source_authority_weight", 0),
        "highest_authority_source": issue.get("highest_authority_source", ""),
        "healthcare_category": issue.get("healthcare_category", ""),
        "classification": issue.get("classification") or {},
        "severity": issue.get("severity", ""),
        "affected_versions": issue.get("affected_versions", []) or [],
        "vendor": issue.get("vendor", ""),
        "generated_by": issue.get("generated_by", "deterministic"),
        # Provenance fields from AI classification / recommendation
        "extracted_facts": issue.get("extracted_facts") or {},
        "inferred_facts": issue.get("inferred_facts") or {},
        "confidence_by_field": issue.get("confidence_by_field") or {},
        "evidence_sources": issue.get("evidence_sources") or [],
        "insufficient_evidence": issue.get("insufficient_evidence", False),
    }
    return entry


def _sort_feed_entries(rows: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
    return sorted(
        rows,
        key=lambda r: (
            -int(r.get("score", 0) or 0),
            str(r.get("last_seen_at", "") or ""),
            str(r.get("issue_id", "") or ""),
        ),
    )


def _rss_pub_date(date_str: str) -> str:
    """Convert YYYY-MM-DD (or ISO 8601) to RFC 2822 for RSS pubDate."""
    if not date_str:
        return ""
    # Strip time portion if present
    ds = date_str[:10]
    try:
        dt = datetime(int(ds[0:4]), int(ds[5:7]), int(ds[8:10]), tzinfo=timezone.utc)
        return dt.strftime("%a, %d %b %Y %H:%M:%S +0000")
    except (ValueError, IndexError):
        return ""


def _write_rss(path: Path, rows: List[Dict[str, Any]], *, top: int = 50) -> None:
    """Write an RSS 2.0 feed of the top *top* scored issues and validate XML."""
    path.parent.mkdir(parents=True, exist_ok=True)

    channel = ET.Element("channel")

    ET.SubElement(channel, "title").text = "AdvisoryOps Community Feed"
    ET.SubElement(channel, "link").text = "https://github.com/advisoryops/advisoryops"
    ET.SubElement(channel, "description").text = (
        "Top-scored healthcare cybersecurity and device-safety advisories"
    )
    now_rfc = datetime.now(tz=timezone.utc).strftime("%a, %d %b %Y %H:%M:%S +0000")
    ET.SubElement(channel, "lastBuildDate").text = now_rfc
    ET.SubElement(channel, "language").text = "en-us"

    for issue in rows[:top]:
        item = ET.SubElement(channel, "item")

        ET.SubElement(item, "title").text = issue.get("title") or ""

        link = issue.get("canonical_link") or ""
        ET.SubElement(item, "link").text = link
        ET.SubElement(item, "guid").text = link or issue.get("issue_id", "")

        published_dates = issue.get("published_dates") or []
        first_date = published_dates[0] if published_dates else ""
        pub_date = _rss_pub_date(first_date)
        if pub_date:
            ET.SubElement(item, "pubDate").text = pub_date

        summary = (issue.get("summary") or "")[:500]
        ET.SubElement(item, "description").text = summary

        priority = issue.get("priority") or ""
        if priority:
            ET.SubElement(item, "category").text = priority

    rss_root = ET.Element("rss", version="2.0")
    rss_root.append(channel)

    xml_bytes = b'<?xml version="1.0" encoding="UTF-8"?>\n' + ET.tostring(
        rss_root, encoding="unicode"
    ).encode("utf-8")

    # Validate before writing
    ET.fromstring(xml_bytes)

    path.write_bytes(xml_bytes)


def _write_csv(path: Path, rows: List[Dict[str, Any]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    fieldnames = [
        "issue_id",
        "issue_type",
        "priority",
        "score",
        "title",
        "canonical_link",
        "cves",
        "sources",
        "published_dates",
        "first_seen_at",
        "last_seen_at",
    ]
    with path.open("w", encoding="utf-8", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        for row in rows:
            writer.writerow(
                {
                    "issue_id": row.get("issue_id", ""),
                    "issue_type": row.get("issue_type", ""),
                    "priority": row.get("priority", ""),
                    "score": row.get("score", 0),
                    "title": row.get("title", ""),
                    "canonical_link": row.get("canonical_link", ""),
                    "cves": ";".join(row.get("cves", []) or []),
                    "sources": ";".join(row.get("sources", []) or []),
                    "published_dates": ";".join(row.get("published_dates", []) or []),
                    "first_seen_at": row.get("first_seen_at", ""),
                    "last_seen_at": row.get("last_seen_at", ""),
                }
            )


def _generate_dashboard(path: Path) -> None:
    """Write the static dashboard HTML file to *path*.

    The dashboard loads ``feed_latest.json``, ``alerts_public.jsonl``, and
    ``meta.json`` via ``fetch()`` from the same directory.  All trust-layer
    sections (handling warnings, evidence gaps, source consensus, evidence
    completeness, extracted/inferred badges, source authority) are rendered
    in the detail panel and gracefully hidden when data is absent.
    """
    html = _DASHBOARD_HTML
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(html, encoding="utf-8", newline="\n")


# The dashboard template is defined as a module-level constant so tests can
# verify its content without invoking the full build pipeline.
_DASHBOARD_HTML = r'''<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>AdvisoryOps — Healthcare Security Intelligence</title>
  <style>
    *, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }

    :root {
      --bg:         #0d1117;
      --surface:    #161b22;
      --surface2:   #21262d;
      --surface3:   #1c2128;
      --border:     #30363d;
      --border2:    #21262d;
      --text:       #e6edf3;
      --text-muted: #8b949e;
      --accent:     #58a6ff;
      --accent-dim: rgba(88, 166, 255, 0.1);

      --p0-bg:   #3d0000; --p0-text: #ff6b6b; --p0-border: #7f0000;
      --p1-bg:   #2d1a00; --p1-text: #ff9a3c; --p1-border: #7a4500;
      --p2-bg:   #2d2500; --p2-text: #f5c542; --p2-border: #7a6000;
      --p3-bg:   #1a1f2e; --p3-text: #94a3b8; --p3-border: #334155;

      --warn-bg:     #3d2800; --warn-border: #7a5200; --warn-text: #ffb347;
      --green-dim:   rgba(63, 185, 80, 0.1);
      --orange-dim:  rgba(255, 154, 60, 0.1);

      --radius: 6px;
      --font: -apple-system, BlinkMacSystemFont, "Segoe UI", system-ui, sans-serif;
      --font-mono: "SFMono-Regular", Consolas, "Liberation Mono", monospace;
    }

    html { scroll-behavior: smooth; }

    body {
      font-family: var(--font);
      background: var(--bg);
      color: var(--text);
      font-size: 14px;
      line-height: 1.5;
      min-height: 100vh;
    }

    /* -- Header --------------------------------------------------- */
    header {
      background: #010409;
      border-bottom: 1px solid var(--border);
      padding: 0 24px;
      position: sticky;
      top: 0;
      z-index: 100;
      box-shadow: 0 1px 0 rgba(88,166,255,0.15);
    }

    .header-inner {
      max-width: 1400px;
      margin: 0 auto;
      display: flex;
      align-items: center;
      gap: 16px;
      height: 56px;
    }

    .logo {
      display: flex;
      align-items: center;
      gap: 10px;
      text-decoration: none;
      flex-shrink: 0;
    }

    .logo-icon {
      width: 28px;
      height: 28px;
      background: linear-gradient(135deg, #1d4ed8, #7c3aed);
      border-radius: 6px;
      display: flex;
      align-items: center;
      justify-content: center;
      font-size: 14px;
      font-weight: 700;
      color: #fff;
      letter-spacing: -0.5px;
    }

    .logo-text {
      font-size: 15px;
      font-weight: 600;
      color: var(--text);
      line-height: 1.2;
    }

    .logo-sub {
      font-size: 10px;
      color: var(--text-muted);
      font-weight: 400;
      letter-spacing: 0.3px;
    }

    .header-meta {
      margin-left: auto;
      display: flex;
      align-items: center;
      gap: 12px;
      font-size: 12px;
      color: var(--text-muted);
      flex-wrap: wrap;
    }

    .source-badge {
      display: inline-flex;
      align-items: center;
      gap: 5px;
      background: var(--accent-dim);
      color: var(--accent);
      border: 1px solid rgba(88,166,255,0.3);
      border-radius: 20px;
      padding: 3px 10px;
      font-size: 12px;
      font-weight: 500;
    }

    .source-badge::before {
      content: "\25CF";
      font-size: 8px;
      animation: pulse 2s infinite;
    }

    @keyframes pulse {
      0%, 100% { opacity: 1; }
      50% { opacity: 0.4; }
    }

    /* -- Main layout ---------------------------------------------- */
    main {
      max-width: 1400px;
      margin: 0 auto;
      padding: 24px;
    }

    /* -- Stat cards ----------------------------------------------- */
    .stats-grid {
      display: grid;
      grid-template-columns: repeat(auto-fit, minmax(160px, 1fr));
      gap: 12px;
      margin-bottom: 24px;
    }

    .stat-card {
      background: var(--surface);
      border: 1px solid var(--border);
      border-radius: var(--radius);
      padding: 16px;
      position: relative;
      overflow: hidden;
    }

    .stat-card::before {
      content: "";
      position: absolute;
      top: 0; left: 0; right: 0;
      height: 2px;
    }

    .stat-card.issues::before { background: var(--accent); }
    .stat-card.alerts::before { background: #f85149; }
    .stat-card.p0::before     { background: var(--p0-text); }
    .stat-card.sources::before { background: #3fb950; }

    .stat-label {
      font-size: 11px;
      color: var(--text-muted);
      text-transform: uppercase;
      letter-spacing: 0.8px;
      font-weight: 600;
      margin-bottom: 6px;
    }

    .stat-value {
      font-size: 28px;
      font-weight: 700;
      line-height: 1;
      font-variant-numeric: tabular-nums;
    }

    .stat-card.issues .stat-value { color: var(--accent); }
    .stat-card.alerts .stat-value { color: #f85149; }
    .stat-card.p0 .stat-value     { color: var(--p0-text); }
    .stat-card.sources .stat-value { color: #3fb950; }

    .stat-sub {
      font-size: 11px;
      color: var(--text-muted);
      margin-top: 4px;
    }

    /* -- Controls ------------------------------------------------- */
    .controls {
      display: flex;
      flex-wrap: wrap;
      gap: 12px;
      margin-bottom: 16px;
      align-items: center;
    }

    .search-wrap {
      position: relative;
      flex: 1;
      min-width: 220px;
    }

    .search-icon {
      position: absolute;
      left: 10px;
      top: 50%;
      transform: translateY(-50%);
      color: var(--text-muted);
      font-size: 14px;
      pointer-events: none;
    }

    .search-input {
      width: 100%;
      background: var(--surface);
      border: 1px solid var(--border);
      border-radius: var(--radius);
      color: var(--text);
      font-family: var(--font);
      font-size: 13px;
      padding: 8px 12px 8px 32px;
      outline: none;
      transition: border-color 0.15s;
    }

    .search-input::placeholder { color: var(--text-muted); }
    .search-input:focus { border-color: var(--accent); box-shadow: 0 0 0 3px rgba(88,166,255,0.1); }

    .filter-pills {
      display: flex;
      gap: 6px;
      flex-wrap: wrap;
    }

    .pill {
      padding: 5px 12px;
      border-radius: 20px;
      border: 1px solid var(--border);
      background: var(--surface);
      color: var(--text-muted);
      font-size: 12px;
      font-weight: 500;
      cursor: pointer;
      transition: all 0.15s;
      white-space: nowrap;
    }

    .pill:hover { border-color: var(--accent); color: var(--accent); }
    .pill.active { background: var(--accent); border-color: var(--accent); color: #000; font-weight: 600; }

    .pill.p0.active { background: var(--p0-text); border-color: var(--p0-text); color: #000; }
    .pill.p1.active { background: var(--p1-text); border-color: var(--p1-text); color: #000; }
    .pill.p2.active { background: var(--p2-text); border-color: var(--p2-text); color: #000; }
    .pill.p3.active { background: #94a3b8; border-color: #94a3b8; color: #000; }
    .pill.healthcare.active { background: #3fb950; border-color: #3fb950; color: #000; }

    /* -- View tabs ------------------------------------------------ */
    .view-tabs {
      display: flex;
      gap: 0;
      border-bottom: 1px solid var(--border);
      margin-bottom: 16px;
    }

    .view-tab {
      padding: 8px 16px;
      border: none;
      background: none;
      color: var(--text-muted);
      font-family: var(--font);
      font-size: 13px;
      font-weight: 500;
      cursor: pointer;
      border-bottom: 2px solid transparent;
      margin-bottom: -1px;
      transition: all 0.15s;
    }

    .view-tab:hover { color: var(--text); }
    .view-tab.active { color: var(--accent); border-bottom-color: var(--accent); }

    .view-tab .tab-count {
      display: inline-block;
      background: var(--surface2);
      border-radius: 10px;
      padding: 1px 7px;
      font-size: 11px;
      margin-left: 5px;
    }

    /* -- Result bar ----------------------------------------------- */
    .result-bar {
      display: flex;
      align-items: center;
      justify-content: space-between;
      margin-bottom: 10px;
      font-size: 12px;
      color: var(--text-muted);
    }

    /* -- Table ---------------------------------------------------- */
    .table-wrap {
      overflow-x: auto;
      border: 1px solid var(--border);
      border-radius: var(--radius);
    }

    table {
      width: 100%;
      border-collapse: collapse;
      min-width: 700px;
    }

    thead {
      background: var(--surface2);
      position: sticky;
      top: 56px;
      z-index: 10;
    }

    th {
      padding: 10px 12px;
      text-align: left;
      font-size: 11px;
      font-weight: 600;
      color: var(--text-muted);
      text-transform: uppercase;
      letter-spacing: 0.6px;
      white-space: nowrap;
      border-bottom: 1px solid var(--border);
      user-select: none;
    }

    th.sortable {
      cursor: pointer;
      transition: color 0.15s;
    }

    th.sortable:hover { color: var(--text); }
    th.sorted { color: var(--accent); }

    th .sort-arrow {
      display: inline-block;
      margin-left: 4px;
      font-size: 10px;
      opacity: 0.5;
    }

    th.sorted .sort-arrow { opacity: 1; }

    tbody tr.data-row {
      border-bottom: 1px solid var(--border2);
      transition: background 0.1s;
      cursor: pointer;
    }

    tbody tr.data-row:last-child { border-bottom: none; }
    tbody tr.data-row:hover { background: var(--surface2); }
    tbody tr.data-row.expanded { background: var(--surface2); }

    td {
      padding: 10px 12px;
      vertical-align: middle;
      font-size: 13px;
    }

    /* Priority badge */
    .badge {
      display: inline-block;
      padding: 2px 8px;
      border-radius: 4px;
      font-size: 11px;
      font-weight: 700;
      border: 1px solid;
      white-space: nowrap;
      letter-spacing: 0.3px;
    }

    .badge.P0 { background: var(--p0-bg); color: var(--p0-text); border-color: var(--p0-border); }
    .badge.P1 { background: var(--p1-bg); color: var(--p1-text); border-color: var(--p1-border); }
    .badge.P2 { background: var(--p2-bg); color: var(--p2-text); border-color: var(--p2-border); }
    .badge.P3 { background: var(--p3-bg); color: var(--p3-text); border-color: var(--p3-border); }

    .score-num {
      font-family: var(--font-mono);
      font-size: 13px;
      font-weight: 600;
      color: var(--text);
    }

    .issue-id {
      font-family: var(--font-mono);
      font-size: 12px;
      color: var(--accent);
    }

    .title-cell {
      max-width: 300px;
    }

    .title-text {
      display: -webkit-box;
      -webkit-line-clamp: 1;
      -webkit-box-orient: vertical;
      overflow: hidden;
      color: var(--text);
    }

    .cves-cell, .sources-cell {
      max-width: 200px;
    }

    .tag {
      display: inline-block;
      background: var(--surface2);
      border: 1px solid var(--border);
      border-radius: 4px;
      padding: 1px 6px;
      font-size: 11px;
      color: var(--text-muted);
      margin: 1px;
      white-space: nowrap;
    }

    .tag.cve {
      color: #a5f3fc;
      border-color: #164e63;
      background: #0c2a35;
    }

    /* Source tier badges */
    .tag.tier-1 { color: #ffd700; border-color: #7a6000; background: #2d2500; font-weight: 600; }
    .tag.tier-2 { color: #c0c0c0; border-color: #555; background: #1e1e1e; }
    .tag.tier-3 { color: #58a6ff; border-color: #1d4ed8; background: #0d1b3e; }
    .tag.tier-4 { color: #8b949e; border-color: #30363d; background: #161b22; }
    .tag.tier-5 { color: #6e7681; border-color: #21262d; background: #0d1117; font-size: 10px; }

    .tier-label {
      font-size: 9px;
      vertical-align: super;
      margin-left: 2px;
      opacity: 0.7;
    }

    .overflow-more {
      font-size: 11px;
      color: var(--text-muted);
      margin-left: 2px;
    }

    .date-cell {
      white-space: nowrap;
      color: var(--text-muted);
      font-size: 12px;
      font-family: var(--font-mono);
    }

    .expand-icon {
      display: inline-block;
      font-size: 10px;
      color: var(--text-muted);
      margin-left: 6px;
      transition: transform 0.2s;
    }

    tr.expanded .expand-icon { transform: rotate(90deg); }

    /* -- Expanded detail row -------------------------------------- */
    tr.detail-row td {
      padding: 0;
      border-bottom: 1px solid var(--border);
    }

    .detail-panel {
      padding: 16px 20px;
      background: var(--surface3);
      display: grid;
      grid-template-columns: 1fr auto;
      gap: 16px;
      align-items: start;
    }

    .detail-summary {
      font-size: 13px;
      color: var(--text);
      line-height: 1.6;
      margin-bottom: 12px;
    }

    .detail-meta {
      display: flex;
      flex-wrap: wrap;
      gap: 16px;
      font-size: 12px;
    }

    .detail-meta-item { display: flex; flex-direction: column; gap: 3px; }
    .detail-meta-label { color: var(--text-muted); font-size: 10px; text-transform: uppercase; letter-spacing: 0.6px; font-weight: 600; }

    .detail-tags { display: flex; flex-wrap: wrap; gap: 4px; }

    .action-badge {
      display: inline-block;
      padding: 2px 8px;
      background: rgba(88,166,255,0.1);
      border: 1px solid rgba(88,166,255,0.3);
      border-radius: 4px;
      font-size: 11px;
      color: var(--accent);
    }

    .detail-actions-col {
      display: flex;
      flex-direction: column;
      gap: 8px;
      align-items: flex-end;
      flex-shrink: 0;
    }

    .btn {
      display: inline-flex;
      align-items: center;
      gap: 5px;
      padding: 7px 14px;
      border-radius: var(--radius);
      font-family: var(--font);
      font-size: 12px;
      font-weight: 500;
      text-decoration: none;
      border: 1px solid;
      cursor: pointer;
      transition: all 0.15s;
      white-space: nowrap;
    }

    .btn-primary {
      background: var(--accent);
      border-color: var(--accent);
      color: #000;
      font-weight: 600;
    }

    .btn-primary:hover { background: #79b8ff; border-color: #79b8ff; }

    .btn-secondary {
      background: transparent;
      border-color: var(--border);
      color: var(--text-muted);
    }

    .btn-secondary:hover { border-color: var(--accent); color: var(--accent); }

    /* Priority left border on expanded */
    .detail-panel[data-priority="P0"] { border-left: 3px solid var(--p0-text); }
    .detail-panel[data-priority="P1"] { border-left: 3px solid var(--p1-text); }
    .detail-panel[data-priority="P2"] { border-left: 3px solid var(--p2-text); }
    .detail-panel[data-priority="P3"] { border-left: 3px solid var(--p3-text); }

    /* -- Trust layer: handling warnings --------------------------- */
    .handling-warnings {
      background: var(--warn-bg);
      border: 1px solid var(--warn-border);
      border-radius: var(--radius);
      padding: 10px 14px;
      margin-bottom: 12px;
    }
    .handling-warnings-title {
      font-size: 11px;
      font-weight: 700;
      text-transform: uppercase;
      letter-spacing: 0.6px;
      color: var(--warn-text);
      margin-bottom: 6px;
    }
    .handling-warnings ul {
      list-style: none;
      padding: 0;
    }
    .handling-warnings li {
      font-size: 12px;
      color: var(--warn-text);
      padding: 2px 0;
    }
    .handling-warnings li::before {
      content: "\26A0\FE0F ";
    }

    /* -- Trust layer: evidence gaps / unknowns -------------------- */
    .evidence-gaps {
      background: var(--surface2);
      border: 1px solid var(--border);
      border-radius: var(--radius);
      margin-bottom: 12px;
    }
    .evidence-gaps-header {
      display: flex;
      align-items: center;
      justify-content: space-between;
      padding: 8px 14px;
      cursor: pointer;
      user-select: none;
    }
    .evidence-gaps-title {
      font-size: 11px;
      font-weight: 700;
      text-transform: uppercase;
      letter-spacing: 0.6px;
      color: var(--text-muted);
    }
    .evidence-gaps-toggle {
      font-size: 10px;
      color: var(--text-muted);
      transition: transform 0.2s;
    }
    .evidence-gaps-body {
      padding: 0 14px 10px;
    }
    .evidence-gaps-body.collapsed {
      display: none;
    }
    .evidence-gaps-body ul {
      list-style: disc;
      padding-left: 16px;
    }
    .evidence-gaps-body li {
      font-size: 12px;
      color: var(--text-muted);
      padding: 1px 0;
    }

    /* -- Trust layer: source consensus ---------------------------- */
    .source-consensus {
      margin-bottom: 12px;
    }
    .consensus-title {
      font-size: 11px;
      font-weight: 700;
      text-transform: uppercase;
      letter-spacing: 0.6px;
      color: var(--text-muted);
      margin-bottom: 6px;
    }
    .consensus-agree {
      background: var(--green-dim);
      border: 1px solid rgba(63,185,80,0.3);
      border-radius: var(--radius);
      padding: 6px 10px;
      margin-bottom: 6px;
    }
    .consensus-agree-label {
      font-size: 10px;
      font-weight: 600;
      color: #3fb950;
      text-transform: uppercase;
      letter-spacing: 0.5px;
      margin-bottom: 3px;
    }
    .consensus-agree li {
      font-size: 12px;
      color: #7ee787;
      list-style: none;
      padding: 1px 0;
    }
    .consensus-disagree {
      background: var(--orange-dim);
      border: 1px solid rgba(255,154,60,0.3);
      border-radius: var(--radius);
      padding: 6px 10px;
    }
    .consensus-disagree-label {
      font-size: 10px;
      font-weight: 600;
      color: var(--p1-text);
      text-transform: uppercase;
      letter-spacing: 0.5px;
      margin-bottom: 3px;
    }
    .consensus-disagree li {
      font-size: 12px;
      color: var(--p1-text);
      list-style: none;
      padding: 1px 0;
    }

    /* -- Trust layer: evidence completeness ----------------------- */
    .evidence-completeness {
      margin-bottom: 12px;
    }
    .evidence-bar-wrap {
      display: flex;
      align-items: center;
      gap: 8px;
    }
    .evidence-bar-label {
      font-size: 11px;
      font-weight: 600;
      color: var(--text-muted);
      white-space: nowrap;
    }
    .evidence-bar {
      flex: 1;
      height: 8px;
      background: var(--surface2);
      border-radius: 4px;
      overflow: hidden;
      max-width: 120px;
    }
    .evidence-bar-fill {
      height: 100%;
      border-radius: 4px;
      transition: width 0.3s;
    }
    .evidence-bar-fill.red    { background: #f85149; }
    .evidence-bar-fill.yellow { background: #f5c542; }
    .evidence-bar-fill.green  { background: #3fb950; }

    /* -- Trust layer: extracted/inferred badges ------------------- */
    .fact-badge {
      display: inline-block;
      padding: 1px 5px;
      border-radius: 3px;
      font-size: 9px;
      font-weight: 600;
      text-transform: uppercase;
      letter-spacing: 0.3px;
      margin-left: 4px;
      vertical-align: middle;
    }
    .fact-badge.extracted {
      background: rgba(88,166,255,0.15);
      color: var(--accent);
      border: 1px solid rgba(88,166,255,0.3);
    }
    .fact-badge.inferred {
      background: var(--surface2);
      color: var(--text-muted);
      border: 1px solid var(--border);
    }

    /* -- Trust layer: source authority badge (list view) ---------- */
    .authority-badge {
      display: inline-flex;
      align-items: center;
      gap: 3px;
      font-size: 10px;
      color: var(--text-muted);
      margin-left: 4px;
      white-space: nowrap;
    }
    .authority-dots {
      letter-spacing: -1px;
      font-size: 9px;
    }
    .authority-dots .filled { color: #ffd700; }
    .authority-dots .empty  { color: var(--border); }

    /* -- Feedback button ------------------------------------------ */
    .feedback-btn {
      display: inline-flex;
      align-items: center;
      gap: 4px;
      padding: 4px 10px;
      border-radius: var(--radius);
      border: 1px solid var(--border);
      background: var(--surface2);
      color: var(--text-muted);
      font-family: var(--font);
      font-size: 11px;
      cursor: pointer;
      transition: all 0.15s;
      white-space: nowrap;
    }
    .feedback-btn:hover { border-color: var(--accent); color: var(--accent); }
    .feedback-btn.flagged { border-color: var(--p1-text); color: var(--p1-text); background: var(--orange-dim); }

    .feedback-dropdown {
      position: relative;
      display: inline-block;
    }
    .feedback-menu {
      display: none;
      position: absolute;
      right: 0;
      top: 100%;
      margin-top: 4px;
      background: var(--surface);
      border: 1px solid var(--border);
      border-radius: var(--radius);
      padding: 4px 0;
      min-width: 180px;
      z-index: 50;
      box-shadow: 0 4px 12px rgba(0,0,0,0.4);
    }
    .feedback-menu.open { display: block; }
    .feedback-menu-item {
      display: block;
      width: 100%;
      padding: 6px 12px;
      border: none;
      background: none;
      color: var(--text);
      font-family: var(--font);
      font-size: 12px;
      text-align: left;
      cursor: pointer;
    }
    .feedback-menu-item:hover { background: var(--surface2); }

    /* -- Disclaimer ----------------------------------------------- */
    .disclaimer-bar {
      font-size: 10px;
      color: var(--text-muted);
      border-top: 1px solid var(--border);
      margin-top: 10px;
      padding-top: 8px;
      font-style: italic;
    }

    /* -- Loading / error states ----------------------------------- */
    .state-box {
      text-align: center;
      padding: 64px 24px;
      color: var(--text-muted);
    }

    .state-box .state-icon {
      font-size: 40px;
      margin-bottom: 16px;
      display: block;
    }

    .state-box h2 { font-size: 18px; color: var(--text); margin-bottom: 8px; }
    .state-box p  { font-size: 13px; max-width: 420px; margin: 0 auto 16px; line-height: 1.6; }

    .state-box code {
      background: var(--surface2);
      border: 1px solid var(--border);
      border-radius: 4px;
      padding: 2px 6px;
      font-family: var(--font-mono);
      font-size: 12px;
      color: var(--accent);
    }

    .spinner {
      width: 32px; height: 32px;
      border: 3px solid var(--border);
      border-top-color: var(--accent);
      border-radius: 50%;
      animation: spin 0.8s linear infinite;
      margin: 0 auto 16px;
    }

    @keyframes spin { to { transform: rotate(360deg); } }

    /* -- Empty state ---------------------------------------------- */
    .empty-row td {
      padding: 48px 24px;
      text-align: center;
      color: var(--text-muted);
      font-size: 13px;
    }

    /* -- Footer --------------------------------------------------- */
    footer {
      max-width: 1400px;
      margin: 32px auto 0;
      padding: 16px 24px;
      border-top: 1px solid var(--border);
      font-size: 11px;
      color: var(--text-muted);
      display: flex;
      justify-content: space-between;
      align-items: center;
      flex-wrap: wrap;
      gap: 8px;
    }

    /* -- Highlight matched text ----------------------------------- */
    mark {
      background: rgba(88,166,255,0.25);
      color: var(--accent);
      border-radius: 2px;
      padding: 0 1px;
    }

    /* -- Responsive ----------------------------------------------- */
    @media (max-width: 700px) {
      main { padding: 12px; }
      .stats-grid { grid-template-columns: repeat(2, 1fr); }
      .detail-panel { grid-template-columns: 1fr; }
      .detail-actions-col { align-items: flex-start; flex-direction: row; flex-wrap: wrap; }
    }
  </style>
</head>
<body>

<header>
  <div class="header-inner">
    <a class="logo" href="#">
      <div class="logo-icon">AO</div>
      <div>
        <div class="logo-text">AdvisoryOps</div>
        <div class="logo-sub">Healthcare Security Intelligence</div>
      </div>
    </a>
    <div class="header-meta">
      <span id="header-source-badge" class="source-badge" style="display:none"></span>
      <span id="header-updated"></span>
    </div>
  </div>
</header>

<main>
  <!-- Stat cards -->
  <div class="stats-grid" id="stats-grid">
    <div class="stat-card issues">
      <div class="stat-label">Total Issues</div>
      <div class="stat-value" id="stat-issues">&mdash;</div>
      <div class="stat-sub">in public feed</div>
    </div>
    <div class="stat-card alerts">
      <div class="stat-label">Alerts</div>
      <div class="stat-value" id="stat-alerts">&mdash;</div>
      <div class="stat-sub">P2+ priority</div>
    </div>
    <div class="stat-card p0">
      <div class="stat-label">Critical (P0)</div>
      <div class="stat-value" id="stat-p0">&mdash;</div>
      <div class="stat-sub">immediate action</div>
    </div>
    <div class="stat-card sources">
      <div class="stat-label">Sources</div>
      <div class="stat-value" id="stat-sources">&mdash;</div>
      <div class="stat-sub">validated feeds</div>
    </div>
  </div>

  <!-- View tabs -->
  <div class="view-tabs">
    <button class="view-tab active" data-view="alerts" onclick="App.setView('alerts')">
      All Alerts <span class="tab-count" id="tab-count-alerts">&mdash;</span>
    </button>
    <button class="view-tab" data-view="latest" onclick="App.setView('latest')">
      Latest 50 <span class="tab-count" id="tab-count-latest">&mdash;</span>
    </button>
  </div>

  <!-- Controls -->
  <div class="controls">
    <div class="search-wrap">
      <span class="search-icon">&#x2315;</span>
      <input
        id="search-input"
        class="search-input"
        type="search"
        placeholder="Search issues, CVEs, titles, summaries..."
        oninput="App.onSearch(this.value)"
      >
    </div>
    <div class="filter-pills" id="filter-pills">
      <button class="pill active" data-priority="all" onclick="App.setFilter('all')">All</button>
      <button class="pill p0" data-priority="P0" onclick="App.setFilter('P0')">P0</button>
      <button class="pill p1" data-priority="P1" onclick="App.setFilter('P1')">P1</button>
      <button class="pill p2" data-priority="P2" onclick="App.setFilter('P2')">P2</button>
      <button class="pill p3" data-priority="P3" onclick="App.setFilter('P3')">P3</button>
      <button class="pill healthcare" data-priority="healthcare" onclick="App.setFilter('healthcare')">Healthcare</button>
    </div>
  </div>

  <!-- Result count bar -->
  <div class="result-bar">
    <span id="result-count"></span>
    <span id="sort-info" style="font-size:11px;"></span>
  </div>

  <!-- Table -->
  <div class="table-wrap" id="table-wrap">
    <div class="state-box">
      <div class="spinner"></div>
      <p>Loading security intelligence data&hellip;</p>
    </div>
  </div>
</main>

<footer>
  <span>AdvisoryOps &mdash; Open Source Healthcare Security Intelligence</span>
  <span id="footer-meta"></span>
</footer>

<script>
(function() {
  'use strict';

  // -- State ---------------------------------------------------------------
  var state = {
    alertsData:  [],
    latestData:  [],
    meta:        {},
    view:        'alerts',
    search:      '',
    priority:    'all',
    sortCol:     'score',
    sortDir:     -1,
    expandedId:  null,
    loaded:      false,
    error:       null,
  };

  // -- Priority rank (for sorting) -----------------------------------------
  var PRIORITY_RANK = { P0: 4, P1: 3, P2: 2, P3: 1 };

  // -- Source tier map ------------------------------------------------------
  var SOURCE_TIERS = {
    'cisa-icsma':1,'cisa-icsa':1,'cisa-kev-json':1,'cisa-kev-csv':1,
    'fda-medwatch':1,'openfda-device-recalls':1,'openfda-device-events':1,
    'certcc-vulnotes':1,'health-canada-recalls':1,
    'abb-psirt':2,'msrc-blog':2,'ncsc-uk':2,'nist-cyber-insights':2,
    'cisa-ncas-alerts':2,'cisa-ncas-analysis':2,'cisa-ncas-current-activity':2,
    'imdrf-consultations':2,'imdrf-documents':2,'imdrf-news':2,
    'zdi-published':2,'zdi-upcoming':2,'nvd-cve-api':2,
    'claroty-team82':3,'armis-labs':3,'asimily-blog':3,'google-project-zero':3,
    'checkpoint-research':3,'talos-intelligence':3,'mandiant-blog':3,
    'crowdstrike-blog':3,'tenable-newest':3,'fortified-health-security':3,
    'dark-reading':4,'krebs-on-security':4,'wired-security':4,
    'security-magazine-cyber':4,'healthcare-it-news-security':4,'hipaa-guide-cyber':4,
    'hit-consultant-cyber':4,'cyberscoop-healthcare':4,'fierce-healthcare':4,
    'medtech-intelligence':4,'bioworld-digital-health':4,'beckers-hospital-cyber':4,
    'compliance-junction-cyber':4,'cshub-attacks':4,'cshub-malware':4,
    'zdnet-security':4,'microsoft-security-blog':4,'sans-isc':4,
    'infosec-malware-analysis':4,'infosec-threat-intel':4,
    'urlhaus-recent':5,'threatfox-iocs':5,'ssl-blacklist':5,'feodo-tracker':5,
    'binary-defense-banlist':5,'ellio-ip-feed':5,'sans-block-ips':5,'bambenek-c2':5,
    'cyber-cure-ips':5,'ecrimelabs-metasploit':5,'epss-data':5,'epss-api':5,
    'vuldb-cti-api':5,'cvefeed-rss':5,
  };

  var TIER_LABELS = { 1:'T1', 2:'T2', 3:'T3', 4:'T4', 5:'T5' };

  var HEALTHCARE_MEDICAL = {
    'cisa-icsma':1,'fda-medwatch':1,'openfda-device-recalls':1,
    'openfda-device-events':1,'health-canada-recalls':1,
  };

  var CVE_ONLY_RE = /^CVE-\d{4}-\d+$/i;

  // -- Helpers --------------------------------------------------------------
  function esc(str) {
    return String(str || '')
      .replace(/&/g,'&amp;').replace(/</g,'&lt;')
      .replace(/>/g,'&gt;').replace(/"/g,'&quot;');
  }

  function highlight(text, query) {
    if (!query) return esc(text);
    var safe = query.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
    return esc(text).replace(
      new RegExp(safe.replace(/&amp;/g,'&amp;amp;'), 'gi'),
      function(m) { return '<mark>' + m + '</mark>'; }
    );
  }

  function fmtDate(dateStr) {
    if (!dateStr) return '\u2014';
    return dateStr.slice(0, 10);
  }

  async function fetchJson(url) {
    var r = await fetch(url);
    if (!r.ok) throw new Error('HTTP ' + r.status + ' loading ' + url);
    return r.json();
  }

  async function fetchJsonl(url) {
    var r = await fetch(url);
    if (!r.ok) throw new Error('HTTP ' + r.status + ' loading ' + url);
    var text = await r.text();
    return text
      .split(/\r?\n/)
      .filter(function(l) { return l.trim(); })
      .map(function(l) { return JSON.parse(l); });
  }

  // -- Evidence completeness scoring ---------------------------------------
  function evidenceScore(row) {
    var s = 0;
    if (row.title) s++;
    if (row.summary) s++;
    if ((row.cves || []).length > 0) s++;
    if (row.severity) s++;
    if ((row.affected_versions || []).length > 0) s++;
    if (row.vendor) s++;
    if ((row.handling_warnings || []).length > 0) s++;
    if ((row.sources || []).length >= 2) s++;
    return s;
  }

  function evidenceColor(score) {
    if (score < 4) return 'red';
    if (score <= 6) return 'yellow';
    return 'green';
  }

  // -- Source authority dots ------------------------------------------------
  function authorityDotsHtml(row) {
    var src = row.highest_authority_source || '';
    var w = Number(row.source_authority_weight) || 0;
    if (!src) return '';
    // Map weight to filled dots: 1.0=4, 0.8=3, 0.6=2, 0.3=1, 0.2=0
    var filled;
    if (w >= 0.95) filled = 4;
    else if (w >= 0.7) filled = 3;
    else if (w >= 0.5) filled = 2;
    else if (w >= 0.2) filled = 1;
    else filled = 0;
    var dots = '';
    for (var i = 0; i < 4; i++) {
      dots += '<span class="' + (i < filled ? 'filled' : 'empty') + '">\u25CF</span>';
    }
    return '<span class="authority-badge">' + esc(src.split('-')[0].toUpperCase())
         + ' <span class="authority-dots">' + dots + '</span></span>';
  }

  // -- Load data ------------------------------------------------------------
  async function loadData() {
    try {
      var results = await Promise.all([
        fetchJson('./meta.json'),
        fetchJson('./feed_latest.json'),
        fetchJsonl('./alerts_public.jsonl'),
      ]);

      state.meta        = results[0];
      state.latestData  = results[1];
      state.alertsData  = results[2];
      state.loaded      = true;

      updateHeader();
      updateStats();
      updateTabCounts();
      render();
    } catch (err) {
      state.error = err.message;
      renderError(err);
    }
  }

  function updateHeader() {
    var sources = state.meta.counts && state.meta.counts.validated_sources;
    var badge = document.getElementById('header-source-badge');
    if (sources) {
      badge.textContent = sources + ' validated sources';
      badge.style.display = 'inline-flex';
    }
    var ts = document.getElementById('header-updated');
    ts.textContent = 'Updated: ' + new Date().toLocaleString();

    var footer = document.getElementById('footer-meta');
    var setName = (state.meta.set_name || '');
    footer.textContent = setName ? 'Dataset: ' + setName : '';
  }

  function updateStats() {
    var c = state.meta.counts || {};
    document.getElementById('stat-issues').textContent  = c.issues_public != null ? c.issues_public : '\u2014';
    document.getElementById('stat-alerts').textContent  = c.alerts_public  != null ? c.alerts_public  : '\u2014';
    document.getElementById('stat-sources').textContent = c.validated_sources != null ? c.validated_sources : '\u2014';
    var p0 = state.alertsData.filter(function(r) { return r.priority === 'P0'; }).length;
    document.getElementById('stat-p0').textContent = p0;
  }

  function updateTabCounts() {
    document.getElementById('tab-count-alerts').textContent = state.alertsData.length;
    document.getElementById('tab-count-latest').textContent = state.latestData.length;
  }

  // -- Filter + sort --------------------------------------------------------
  function currentData() {
    return state.view === 'alerts' ? state.alertsData : state.latestData;
  }

  function filteredData() {
    var rows = currentData();
    var q = state.search.toLowerCase().trim();
    var pf = state.priority;

    if (pf === 'healthcare') {
      rows = rows.filter(function(r) { return (r.sources || []).some(function(s) { return HEALTHCARE_MEDICAL[s]; }); });
    } else if (pf !== 'all') {
      rows = rows.filter(function(r) { return r.priority === pf; });
    }

    if (q) {
      rows = rows.filter(function(r) {
        var text = [
          r.issue_id,
          r.title,
          r.summary,
        ].concat(r.cves || []).concat(r.sources || []).join(' ').toLowerCase();
        return text.indexOf(q) !== -1;
      });
    }

    return sortRows(rows);
  }

  function sortRows(rows) {
    var col = state.sortCol;
    var dir = state.sortDir;
    return rows.slice().sort(function(a, b) {
      var va, vb;
      switch (col) {
        case 'priority':
          va = PRIORITY_RANK[a.priority] || 0;
          vb = PRIORITY_RANK[b.priority] || 0;
          break;
        case 'score':
          va = Number(a.score) || 0;
          vb = Number(b.score) || 0;
          break;
        case 'issue_id':
          va = String(a.issue_id || '').toLowerCase();
          vb = String(b.issue_id || '').toLowerCase();
          break;
        case 'title':
          va = String(a.title || '').toLowerCase();
          vb = String(b.title || '').toLowerCase();
          break;
        case 'published':
          va = (a.published_dates || [])[0] || '';
          vb = (b.published_dates || [])[0] || '';
          break;
        default:
          va = Number(a.score) || 0;
          vb = Number(b.score) || 0;
      }
      if (va < vb) return -dir;
      if (va > vb) return dir;
      return 0;
    });
  }

  // -- Render ---------------------------------------------------------------
  function render() {
    if (!state.loaded) return;
    var rows = filteredData();
    var total = currentData().length;

    document.getElementById('result-count').textContent =
      'Showing ' + rows.length.toLocaleString() + ' of ' + total.toLocaleString() + ' issues';
    document.getElementById('sort-info').textContent =
      'Sorted by: ' + state.sortCol + ' ' + (state.sortDir === -1 ? '\u2193' : '\u2191');

    document.getElementById('table-wrap').innerHTML = buildTable(rows, state.search);
  }

  function buildTable(rows, q) {
    var cols = [
      { key: 'priority', label: 'Priority', sortable: true },
      { key: 'score',    label: 'Score',    sortable: true },
      { key: 'issue_id', label: 'Issue ID', sortable: true },
      { key: 'title',    label: 'Title',    sortable: true },
      { key: 'cves',     label: 'CVEs',     sortable: false },
      { key: 'sources',  label: 'Sources',  sortable: false },
      { key: 'published',label: 'Published',sortable: true },
    ];

    var thead = '<thead><tr>' + cols.map(function(c) {
      var isSorted = state.sortCol === c.key;
      var arrow = isSorted ? (state.sortDir === -1 ? '\u25BC' : '\u25B2') : '\u25B2';
      var cls = [
        c.sortable ? 'sortable' : '',
        isSorted ? 'sorted' : '',
      ].filter(Boolean).join(' ');
      var click = c.sortable ? 'onclick="App.setSort(\'' + c.key + '\')"' : '';
      return '<th class="' + cls + '" ' + click + '>' + esc(c.label)
           + (c.sortable ? '<span class="sort-arrow">' + arrow + '</span>' : '') + '</th>';
    }).join('') + '</tr></thead>';

    if (rows.length === 0) {
      return '<table>' + thead + '<tbody>'
        + '<tr class="empty-row"><td colspan="' + cols.length + '">'
        + 'No issues match your current filters.'
        + '</td></tr></tbody></table>';
    }

    var tbody = rows.map(function(row) { return buildRow(row, q); }).join('');
    return '<table>' + thead + '<tbody>' + tbody + '</tbody></table>';
  }

  function buildRow(row, q) {
    var id = esc(row.issue_id || '');
    var priority = row.priority || 'P3';
    var score = row.score != null ? row.score : '\u2014';
    var isExpanded = state.expandedId === row.issue_id;

    var cves = (row.cves || []).slice(0, 3);
    var cvesExtra = (row.cves || []).length - 3;
    var cveHtml = cves.map(function(c) { return '<span class="tag cve">' + esc(c) + '</span>'; }).join('')
      + (cvesExtra > 0 ? '<span class="overflow-more">+' + cvesExtra + '</span>' : '');

    var sources = (row.sources || []).slice(0, 2);
    var srcExtra = (row.sources || []).length - 2;
    var srcHtml = sources.map(function(s) {
      var t = SOURCE_TIERS[s];
      var tc = t ? ' tier-' + t : '';
      var tl = t ? '<span class="tier-label">' + TIER_LABELS[t] + '</span>' : '';
      return '<span class="tag' + tc + '">' + esc(s) + tl + '</span>';
    }).join('') + (srcExtra > 0 ? '<span class="overflow-more">+' + srcExtra + '</span>' : '');

    var pubDate = fmtDate((row.published_dates || [])[0]);

    var rawTitle = row.title || row.issue_id || '';
    var titleHl = highlight(rawTitle, q);
    if (CVE_ONLY_RE.test(rawTitle.trim()) && row.summary) {
      var sub = row.summary.slice(0, 80).trim();
      titleHl += '<br><span style="font-size:11px;color:var(--text-muted);font-family:var(--font)">'
        + esc(sub) + (row.summary.length > 80 ? '\u2026' : '') + '</span>';
    }
    var idHl = highlight(row.issue_id || '', q);

    // Source authority badge in list view
    var authBadge = authorityDotsHtml(row);

    var expandedClass = isExpanded ? ' expanded' : '';

    var dataRow = '<tr class="data-row' + expandedClass + '" onclick="App.toggleExpand(\''
      + (row.issue_id || '').replace(/'/g, "\\'") + '\')" title="Click to expand">'
      + '<td><span class="badge ' + priority + '">' + priority + '</span></td>'
      + '<td><span class="score-num">' + score + '</span></td>'
      + '<td><span class="issue-id">' + idHl + '</span>' + authBadge + '</td>'
      + '<td class="title-cell"><span class="title-text">' + titleHl + '</span><span class="expand-icon">\u25B6</span></td>'
      + '<td class="cves-cell">' + (cveHtml || '<span style="color:var(--text-muted)">\u2014</span>') + '</td>'
      + '<td class="sources-cell">' + (srcHtml || '<span style="color:var(--text-muted)">\u2014</span>') + '</td>'
      + '<td class="date-cell">' + pubDate + '</td>'
      + '</tr>';

    var detailRow = isExpanded ? buildDetailRow(row, q) : '';
    return dataRow + detailRow;
  }

  function buildDetailRow(row, q) {
    var priority = row.priority || 'P3';
    var rawSummary = row.summary || 'No summary available.';
    var TRUNC = 250;
    var summaryHtml;
    if (rawSummary.length > TRUNC) {
      var shortHl = highlight(rawSummary.slice(0, TRUNC), q);
      var fullHl  = highlight(rawSummary, q);
      var uid = 'sum_' + (row.issue_id || '').replace(/[^a-z0-9]/gi, '_');
      summaryHtml = '<span id="' + uid + '_short">' + shortHl + '<span style="color:var(--text-muted)">\u2026 </span>'
        + '<button onclick="event.stopPropagation();document.getElementById(\'' + uid + '_short\').style.display=\'none\';document.getElementById(\'' + uid + '_full\').style.display=\'inline\'" '
        + 'style="background:none;border:none;color:var(--accent);font-size:11px;cursor:pointer;padding:0">Show more</button></span>'
        + '<span id="' + uid + '_full" style="display:none">' + fullHl + ' '
        + '<button onclick="event.stopPropagation();document.getElementById(\'' + uid + '_full\').style.display=\'none\';document.getElementById(\'' + uid + '_short\').style.display=\'inline\'" '
        + 'style="background:none;border:none;color:var(--accent);font-size:11px;cursor:pointer;padding:0">Show less</button></span>';
    } else {
      summaryHtml = highlight(rawSummary, q);
    }

    var cveLinks = (row.cves || []).map(function(cve) {
      return '<a href="https://nvd.nist.gov/vuln/detail/' + esc(cve) + '" target="_blank" rel="noopener" class="tag cve" style="text-decoration:none">' + esc(cve) + ' \u2197</a>';
    }).join('') || '<span class="tag">No CVEs</span>';

    var sourceTags = (row.sources || []).map(function(s) {
      var t = SOURCE_TIERS[s];
      var tc = t ? ' tier-' + t : '';
      var tl = t ? '<span class="tier-label">' + TIER_LABELS[t] + '</span>' : '';
      return '<span class="tag' + tc + '">' + esc(s) + tl + '</span>';
    }).join('') || '\u2014';

    var actionBadges = (row.actions || []).map(function(a) {
      return '<span class="action-badge">' + esc(a) + '</span>';
    }).join('');

    var firstSeen = row.first_seen_at ? row.first_seen_at.slice(0,10) : '\u2014';
    var lastSeen  = row.last_seen_at  ? row.last_seen_at.slice(0,10)  : '\u2014';

    var canonLink = row.canonical_link
      ? '<a href="' + esc(row.canonical_link) + '" target="_blank" rel="noopener" class="btn btn-primary">View Advisory \u2197</a>'
      : '';

    // --- TRUST LAYER SECTIONS ---

    // 1. Handling Warnings (highest priority)
    var handlingHtml = '';
    var hw = row.handling_warnings || [];
    if (hw.length > 0) {
      handlingHtml = '<div class="handling-warnings">'
        + '<div class="handling-warnings-title">Device Handling Warnings</div>'
        + '<ul>' + hw.map(function(w) { return '<li>' + esc(w) + '</li>'; }).join('') + '</ul>'
        + '</div>';
    }

    // 2. Evidence Gaps / Unknowns ("What We Don't Know")
    var gapsHtml = '';
    var gaps = (row.evidence_gaps || []).concat(row.unknowns || []);
    // Deduplicate
    var seen = {};
    gaps = gaps.filter(function(g) {
      if (!g || seen[g]) return false;
      seen[g] = true;
      return true;
    });
    if (gaps.length > 0) {
      var gapUid = 'gaps_' + (row.issue_id || '').replace(/[^a-z0-9]/gi, '_');
      gapsHtml = '<div class="evidence-gaps">'
        + '<div class="evidence-gaps-header" onclick="event.stopPropagation();var b=document.getElementById(\'' + gapUid + '\');b.classList.toggle(\'collapsed\');this.querySelector(\'.evidence-gaps-toggle\').textContent=b.classList.contains(\'collapsed\')?\'\u25B6\':\'\u25BC\'">'
        + '<span class="evidence-gaps-title">What We Don\'t Know</span>'
        + '<span class="evidence-gaps-toggle">\u25BC</span>'
        + '</div>'
        + '<div id="' + gapUid + '" class="evidence-gaps-body">'
        + '<ul>' + gaps.map(function(g) { return '<li>' + esc(g) + '</li>'; }).join('') + '</ul>'
        + '</div>'
        + '</div>';
    }

    // 3. Source Consensus
    var consensusHtml = '';
    var sc = row.source_consensus || {};
    var agreed = sc.agreed || [];
    var contradicted = sc.contradicted || [];
    if (agreed.length > 0 || contradicted.length > 0) {
      consensusHtml = '<div class="source-consensus">'
        + '<div class="consensus-title">Source Consensus</div>';
      if (agreed.length > 0) {
        consensusHtml += '<div class="consensus-agree">'
          + '<div class="consensus-agree-label">Sources Agree On:</div>'
          + '<ul>' + agreed.map(function(a) { return '<li>' + esc(typeof a === 'string' ? a : JSON.stringify(a)) + '</li>'; }).join('') + '</ul>'
          + '</div>';
      }
      if (contradicted.length > 0) {
        consensusHtml += '<div class="consensus-disagree">'
          + '<div class="consensus-disagree-label">Sources Disagree On:</div>'
          + '<ul>' + contradicted.map(function(c) {
            if (typeof c === 'object' && c !== null) {
              return '<li><strong>' + esc(c.field || '') + '</strong>: ' + esc(c.source_a || '') + ' vs ' + esc(c.source_b || '') + '</li>';
            }
            return '<li>' + esc(String(c)) + '</li>';
          }).join('') + '</ul>'
          + '</div>';
      }
      consensusHtml += '</div>';
    }

    // 4. Evidence Completeness
    var evScore = evidenceScore(row);
    var evColor = evidenceColor(evScore);
    var evPct = Math.round((evScore / 8) * 100);
    var evidenceHtml = '<div class="evidence-completeness">'
      + '<div class="evidence-bar-wrap">'
      + '<span class="evidence-bar-label">Evidence: ' + evScore + '/8</span>'
      + '<div class="evidence-bar"><div class="evidence-bar-fill ' + evColor + '" style="width:' + evPct + '%"></div></div>'
      + '</div></div>';

    // 5. Extracted vs Inferred badges
    var clf = row.classification || {};
    var extractedFacts = clf.extracted_facts || {};
    var inferredFacts  = clf.inferred_facts  || {};
    var factBadgesHtml = '';
    var eKeys = Object.keys(extractedFacts);
    var iKeys = Object.keys(inferredFacts);
    if (eKeys.length > 0 || iKeys.length > 0) {
      factBadgesHtml = '<div class="detail-meta-item" style="margin-top:8px">'
        + '<span class="detail-meta-label">AI Attribution</span><div class="detail-tags">';
      eKeys.forEach(function(k) {
        factBadgesHtml += '<span class="tag">' + esc(k) + ': ' + esc(String(extractedFacts[k])) + '<span class="fact-badge extracted">extracted</span></span>';
      });
      iKeys.forEach(function(k) {
        factBadgesHtml += '<span class="tag">' + esc(k) + ': ' + esc(String(inferredFacts[k])) + '<span class="fact-badge inferred">inferred</span></span>';
      });
      factBadgesHtml += '</div></div>';
    }

    return '<tr class="detail-row">'
      + '<td colspan="7">'
      + '<div class="detail-panel" data-priority="' + priority + '">'
      + '<div>'
      + handlingHtml
      + '<div class="detail-summary">' + summaryHtml + '</div>'
      + evidenceHtml
      + gapsHtml
      + consensusHtml
      + '<div class="detail-meta">'
      + '<div class="detail-meta-item">'
      + '<span class="detail-meta-label">CVEs</span>'
      + '<div class="detail-tags">' + cveLinks + '</div>'
      + '</div>'
      + '<div class="detail-meta-item">'
      + '<span class="detail-meta-label">Sources</span>'
      + '<div class="detail-tags">' + sourceTags + '</div>'
      + '</div>'
      + '<div class="detail-meta-item">'
      + '<span class="detail-meta-label">Actions</span>'
      + '<div class="detail-tags">' + (actionBadges || '\u2014') + '</div>'
      + '</div>'
      + '<div class="detail-meta-item">'
      + '<span class="detail-meta-label">First Seen</span>'
      + '<span style="font-family:var(--font-mono);font-size:12px">' + firstSeen + '</span>'
      + '</div>'
      + '<div class="detail-meta-item">'
      + '<span class="detail-meta-label">Last Seen</span>'
      + '<span style="font-family:var(--font-mono);font-size:12px">' + lastSeen + '</span>'
      + '</div>'
      + factBadgesHtml
      + '</div>'
      + '<div class="disclaimer-bar">AI-assisted guidance based on approved mitigation patterns and cited standards. Verify against vendor documentation and local operational constraints before implementation.</div>'
      + '</div>'
      + '<div class="detail-actions-col">'
      + canonLink
      + buildFeedbackButton(row)
      + '<button class="btn btn-secondary" onclick="event.stopPropagation();App.toggleExpand(\'' + (row.issue_id || '').replace(/'/g, "\\'") + '\')">Collapse</button>'
      + '</div>'
      + '</div>'
      + '</td>'
      + '</tr>';
  }

  // -- Feedback button builder -----------------------------------------------
  function buildFeedbackButton(row) {
    var iid = (row.issue_id || '').replace(/'/g, "\\'");
    var fbKey = 'ao_feedback_' + iid;
    var existing = null;
    try { existing = localStorage.getItem(fbKey); } catch(e) {}
    if (existing) {
      return '<span class="feedback-btn flagged" title="Feedback submitted">Flagged</span>';
    }
    var uid = 'fb_' + (row.issue_id || '').replace(/[^a-z0-9]/gi, '_');
    return '<div class="feedback-dropdown">'
      + '<button class="feedback-btn" onclick="event.stopPropagation();var m=document.getElementById(\'' + uid + '\');m.classList.toggle(\'open\')">'
      + 'Flag this recommendation</button>'
      + '<div id="' + uid + '" class="feedback-menu">'
      + ['incorrect','too_aggressive','too_conservative','missing_context','helpful'].map(function(t) {
        return '<button class="feedback-menu-item" onclick="event.stopPropagation();App.submitFeedback(\'' + iid + '\',\'' + t + '\')">' + t.replace(/_/g,' ') + '</button>';
      }).join('')
      + '</div></div>';
  }

  function renderError(err) {
    document.getElementById('table-wrap').innerHTML =
      '<div class="state-box">'
      + '<span class="state-icon">\u26A0</span>'
      + '<h2>Could not load data</h2>'
      + '<p>' + esc(err.message) + '</p>'
      + '<p>The dashboard must be served over HTTP. Run:<br>'
      + '<code>python -m http.server 8080</code><br>'
      + 'from the <code>outputs/community_public/</code> directory, then open<br>'
      + '<code>http://localhost:8080/dashboard.html</code>'
      + '</p></div>';
  }

  // -- Public API -----------------------------------------------------------
  window.App = {
    setView: function(view) {
      state.view = view;
      state.expandedId = null;
      document.querySelectorAll('.view-tab').forEach(function(t) {
        t.classList.toggle('active', t.dataset.view === view);
      });
      render();
    },
    onSearch: function(val) {
      state.search = val;
      state.expandedId = null;
      render();
    },
    setFilter: function(priority) {
      state.priority = priority;
      state.expandedId = null;
      document.querySelectorAll('.pill').forEach(function(p) {
        p.classList.toggle('active', p.dataset.priority === priority);
      });
      render();
    },
    setSort: function(col) {
      if (state.sortCol === col) {
        state.sortDir *= -1;
      } else {
        state.sortCol = col;
        state.sortDir = col === 'issue_id' || col === 'title' ? 1 : -1;
      }
      render();
    },
    toggleExpand: function(id) {
      state.expandedId = state.expandedId === id ? null : id;
      render();
    },
    submitFeedback: function(issueId, feedbackType) {
      var entry = {
        issue_id: issueId,
        feedback_type: feedbackType,
        timestamp: new Date().toISOString(),
      };
      try {
        localStorage.setItem('ao_feedback_' + issueId, JSON.stringify(entry));
      } catch(e) {}
      // Collect all feedback for download
      var all = [];
      try {
        var raw = localStorage.getItem('ao_feedback_all');
        if (raw) all = JSON.parse(raw);
      } catch(e) {}
      all.push(entry);
      try { localStorage.setItem('ao_feedback_all', JSON.stringify(all)); } catch(e) {}
      render();
    },
  };

  // -- Boot -----------------------------------------------------------------
  loadData();
})();
</script>
</body>
</html>
'''


def build_community_feed(
    *,
    set_id: str = "gold_pass1",
    refresh: bool = False,
    refresh_limit: int = 10,
    out_root_discover: str = "outputs/discover",
    out_root_runs: str = "outputs/source_runs",
    out_root_community: str = "outputs/community_public",
    only_new: bool = False,
    limit_per_source: int = 200,
    limit_issues: int = 0,
    min_priority: str = "P2",
    top: int = 100,
    latest: int = 50,
    recommend: bool = False,
    recommend_model: str = "gpt-4o-mini",
    recommend_priorities: Sequence[str] = ("P0", "P1"),
    ai_score: bool = False,
    ai_score_model: str = "gpt-4o-mini",
    _recommend_call_fn: Optional[Callable] = None,
    _ai_classify_fn: Optional[Callable] = None,
) -> Tuple[Path, Path, Path]:
    if latest <= 0:
        raise ValueError("--latest must be > 0")

    manifest = load_community_manifest()
    selected_set = manifest.get_set(set_id)
    cfg = load_sources_config()
    cfg_by_id = {s.source_id: s for s in cfg.sources}

    if refresh:
        for source_id in selected_set.source_ids:
            print("")
            print(f"Refreshing source: {source_id}")
            source_run(
                source_id,
                limit=refresh_limit,
                ingest=False,
                dry_run=False,
                ingest_mode="new",
                out_root_discover=out_root_discover,
                out_root_runs=out_root_runs,
                show_links=False,
                reset_state=False,
            )

    community_root = Path(out_root_community)
    community_root.mkdir(parents=True, exist_ok=True)

    correlate_root = community_root / "correlate"
    scored_root = community_root / "scored"

    issues_path, _ = correlate(
        out_root_discover=out_root_discover,
        out_root_issues=str(correlate_root),
        sources=selected_set.source_ids,
        only_new=only_new,
        limit_per_source=limit_per_source,
        limit_issues=limit_issues,
        dry_run=False,
    )
    if issues_path is None:
        raise RuntimeError("Correlate did not produce issues output")

    _, alerts_path, _ = score_issues(
        in_issues=str(issues_path),
        out_root_scored=str(scored_root),
        min_priority=min_priority,
        top=top,
        ai_score=ai_score,
        ai_score_model=ai_score_model,
        _ai_classify_fn=_ai_classify_fn,
    )

    scored_rows = _read_jsonl(scored_root / "issues_scored.jsonl")
    alert_rows = _read_jsonl(alerts_path)

    # --- Run contradiction detector on issues with 2+ sources ---
    from .contradiction_detector import detect_contradictions

    scored_rows = detect_contradictions(scored_rows)
    # Also annotate alert_rows (they're a subset of scored_rows by issue_id)
    consensus_by_id = {r["issue_id"]: r.get("source_consensus", {}) for r in scored_rows}
    for ar in alert_rows:
        iid = ar.get("issue_id", "")
        if iid in consensus_by_id:
            ar["source_consensus"] = consensus_by_id[iid]

    feed_rows = _sort_feed_entries([_feed_entry(r) for r in scored_rows])
    latest_rows = feed_rows[:latest]
    alert_feed_rows = _sort_feed_entries([_feed_entry(r) for r in alert_rows])

    # --- Optional recommendation pass ---
    packets_dir: Optional[Path] = None
    packet_count = 0

    # Collect recommendation trust data to merge back into feed entries
    packet_trust_by_id: Dict[str, Dict[str, Any]] = {}

    if recommend:
        from .playbook import load_playbook
        from .recommend import recommend_mitigations
        from .packet_export import export_json, _safe_stem

        pb = load_playbook()
        packets_dir = community_root / "packets"
        packets_dir.mkdir(parents=True, exist_ok=True)

        priority_set = set(recommend_priorities)
        target_issues = [r for r in alert_rows if r.get("priority") in priority_set]
        print(f"\n  Recommend: generating packets for {len(target_issues)} alerts "
              f"(priorities: {', '.join(sorted(priority_set))})")

        for issue in target_issues:
            issue_id = issue.get("issue_id", "unknown")
            try:
                packet = recommend_mitigations(
                    issue,
                    pb,
                    model=recommend_model,
                    _call_fn=_recommend_call_fn,
                )
                stem = _safe_stem(issue_id)
                export_json(packet, packets_dir / f"{stem}_packet.json")
                packet_count += 1
                cached_label = " (cached)" if packet.from_cache else ""
                print(f"    Wrote packet: {issue_id}{cached_label}")

                # Collect trust fields from recommendation for merge-back
                packet_trust_by_id[issue_id] = {
                    "handling_warnings": packet.handling_warnings or [],
                    "evidence_gaps": packet.evidence_gaps or [],
                    "extracted_facts": packet.extracted_facts or {},
                    "inferred_facts": packet.inferred_facts or {},
                    "confidence_by_field": packet.confidence_by_field or {},
                    "evidence_sources": packet.evidence_sources or [],
                    "reasoning": packet.reasoning or "",
                    "generated_by": "ai",
                }
            except Exception as exc:
                print(f"    Warning: recommend failed for {issue_id}: {exc}")

        print(f"  Recommend: {packet_count}/{len(target_issues)} packets written")

    # --- Merge recommendation trust data back into feed rows ---
    if packet_trust_by_id:
        def _merge_trust(rows: List[Dict[str, Any]]) -> None:
            for row in rows:
                iid = row.get("issue_id", "")
                if iid not in packet_trust_by_id:
                    continue
                pkt = packet_trust_by_id[iid]
                # Merge list fields (deduplicate)
                for list_field in ("handling_warnings", "evidence_gaps"):
                    existing = set(row.get(list_field) or [])
                    for v in pkt.get(list_field, []):
                        if v not in existing:
                            row.setdefault(list_field, []).append(v)
                            existing.add(v)
                # evidence_gaps also populate unknowns (what we don't know)
                unknowns_existing = set(row.get("unknowns") or [])
                for v in pkt.get("evidence_gaps", []):
                    if v not in unknowns_existing:
                        row.setdefault("unknowns", []).append(v)
                        unknowns_existing.add(v)
                # Merge/overwrite dict fields (recommendation is more specific)
                for dict_field in ("extracted_facts", "inferred_facts", "confidence_by_field"):
                    existing_d = row.get(dict_field) or {}
                    pkt_d = pkt.get(dict_field) or {}
                    if pkt_d:
                        merged = {**existing_d, **pkt_d}
                        row[dict_field] = merged
                # Merge evidence_sources (deduplicate)
                existing_sources = set(row.get("evidence_sources") or [])
                for s in pkt.get("evidence_sources", []):
                    if s not in existing_sources:
                        row.setdefault("evidence_sources", []).append(s)
                        existing_sources.add(s)
                row["generated_by"] = "ai"

        _merge_trust(feed_rows)
        _merge_trust(alert_feed_rows)
        _merge_trust(latest_rows)

    out_issues_public = community_root / "issues_public.jsonl"
    out_alerts_public = community_root / "alerts_public.jsonl"
    out_latest = community_root / "feed_latest.json"
    out_csv = community_root / "feed.csv"
    out_rss = community_root / "feed.xml"
    out_sources = community_root / "validated_sources.json"
    out_meta = community_root / "meta.json"
    out_dashboard = community_root / "dashboard.html"

    _write_jsonl(out_issues_public, feed_rows)
    _write_jsonl(out_alerts_public, alert_feed_rows)
    out_latest.write_text(json.dumps(latest_rows, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    _write_csv(out_csv, feed_rows)
    _write_rss(out_rss, feed_rows, top=50)
    _generate_dashboard(out_dashboard)

    validated_sources = []
    for source_id in selected_set.source_ids:
        src = cfg_by_id[source_id]
        validated_sources.append(
            {
                "source_id": src.source_id,
                "name": src.name,
                "scope": src.scope,
                "page_type": src.page_type,
                "entry_url": src.entry_url,
                "enabled": src.enabled,
                "status": "validated",
            }
        )
    for source_id in manifest.candidate_sources:
        src = cfg_by_id[source_id]
        validated_sources.append(
            {
                "source_id": src.source_id,
                "name": src.name,
                "scope": src.scope,
                "page_type": src.page_type,
                "entry_url": src.entry_url,
                "enabled": src.enabled,
                "status": "candidate",
            }
        )
    out_sources.write_text(json.dumps(validated_sources, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")

    meta = {
        "set_id": selected_set.set_id,
        "set_name": selected_set.name,
        "description": selected_set.description,
        "out_root_discover": out_root_discover,
        "out_root_runs": out_root_runs,
        "out_root_community": str(community_root),
        "params": {
            "refresh": bool(refresh),
            "refresh_limit": int(refresh_limit),
            "only_new": bool(only_new),
            "limit_per_source": int(limit_per_source),
            "limit_issues": int(limit_issues),
            "min_priority": min_priority,
            "top": int(top),
            "latest": int(latest),
        },
        "counts": {
            "validated_sources": len(selected_set.source_ids),
            "candidate_sources": len(manifest.candidate_sources),
            "issues_public": len(feed_rows),
            "alerts_public": len(alert_feed_rows),
            "latest": len(latest_rows),
            "packets": packet_count,
        },
        "outputs": {
            "issues_public_jsonl": str(out_issues_public),
            "alerts_public_jsonl": str(out_alerts_public),
            "feed_latest_json": str(out_latest),
            "feed_csv": str(out_csv),
            "feed_rss_xml": str(out_rss),
            "validated_sources_json": str(out_sources),
            "meta_json": str(out_meta),
            "dashboard_html": str(out_dashboard),
            "packets_dir": str(packets_dir) if packets_dir else None,
        },
    }
    out_meta.write_text(json.dumps(meta, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")

    print("")
    print("Community build summary:")
    print(f"  Set:              {selected_set.set_id} ({selected_set.name})")
    print(f"  Validated:        {len(selected_set.source_ids)}")
    print(f"  Candidates:       {len(manifest.candidate_sources)}")
    print(f"  Issues public:    {len(feed_rows)}")
    print(f"  Alerts public:    {len(alert_feed_rows)}")
    print(f"  Latest entries:   {len(latest_rows)}")
    print(f"  Wrote:            {out_issues_public}")
    print(f"  Wrote:            {out_alerts_public}")
    print(f"  Wrote:            {out_latest}")
    print(f"  Wrote:            {out_csv}")
    print(f"  Wrote:            {out_rss}")
    print(f"  Wrote:            {out_dashboard}")
    print(f"  Wrote:            {out_sources}")
    print(f"  Wrote:            {out_meta}")
    if packets_dir:
        print(f"  Packets dir:      {packets_dir} ({packet_count} packets)")

    return out_issues_public, out_alerts_public, out_meta
