"""Excel (.xlsx) export for AdvisoryOps issue feeds.

Produces a formatted workbook with frozen header row, auto-width columns,
color-coded priority column, and wrapped summary text.

Usage::

    from advisoryops.excel_export import export_excel
    export_excel(issues, Path("issues_public.xlsx"))

CLI::

    advisoryops export-excel --issues-path issues.jsonl --out issues.xlsx
"""
from __future__ import annotations

from pathlib import Path
from typing import Any, Dict, List

from openpyxl import Workbook
from openpyxl.styles import Alignment, Font, PatternFill
from openpyxl.utils import get_column_letter


# Priority → fill color mapping
_PRIORITY_FILLS: Dict[str, PatternFill] = {
    "P0": PatternFill(start_color="FF4444", end_color="FF4444", fill_type="solid"),
    "P1": PatternFill(start_color="FF8C00", end_color="FF8C00", fill_type="solid"),
    "P2": PatternFill(start_color="FFD700", end_color="FFD700", fill_type="solid"),
    "P3": PatternFill(start_color="CCCCCC", end_color="CCCCCC", fill_type="solid"),
}

_PRIORITY_FONTS: Dict[str, Font] = {
    "P0": Font(bold=True, color="FFFFFF"),
    "P1": Font(bold=True, color="FFFFFF"),
    "P2": Font(bold=True, color="000000"),
    "P3": Font(color="333333"),
}

COLUMNS = [
    "Issue ID",
    "Priority",
    "Score",
    "Title",
    "Summary",
    "CVEs",
    "Sources",
    "Vendor",
    "Severity",
    "Handling Warnings",
    "Evidence Gaps",
    "Evidence Completeness",
    "Generated By",
]


def _pick(issue: Dict[str, Any], *keys: str) -> str:
    """Return first non-empty string value found in *keys*."""
    for k in keys:
        v = issue.get(k)
        if v is not None:
            if isinstance(v, list):
                return ", ".join(str(x) for x in v)
            return str(v)
    return ""


def _row(issue: Dict[str, Any]) -> List[str]:
    """Extract one spreadsheet row from an issue dict."""
    return [
        _pick(issue, "issue_id"),
        _pick(issue, "priority"),
        _pick(issue, "score"),
        _pick(issue, "title"),
        _pick(issue, "summary", "ai_summary"),
        _pick(issue, "cves"),
        _pick(issue, "sources"),
        _pick(issue, "vendor"),
        _pick(issue, "severity"),
        _pick(issue, "handling_warnings"),
        _pick(issue, "evidence_gaps"),
        _pick(issue, "evidence_completeness"),
        _pick(issue, "generated_by"),
    ]


def export_excel(issues: List[Dict[str, Any]], out_path: Path) -> Path:
    """Write *issues* to a formatted ``.xlsx`` file at *out_path*.

    Returns the resolved output path.
    """
    out_path = Path(out_path)
    out_path.parent.mkdir(parents=True, exist_ok=True)

    wb = Workbook()
    ws = wb.active
    ws.title = "Issues"

    # ---- header row ----
    header_font = Font(bold=True, color="FFFFFF")
    header_fill = PatternFill(start_color="333333", end_color="333333", fill_type="solid")

    for col_idx, col_name in enumerate(COLUMNS, start=1):
        cell = ws.cell(row=1, column=col_idx, value=col_name)
        cell.font = header_font
        cell.fill = header_fill
        cell.alignment = Alignment(horizontal="center", vertical="center")

    ws.freeze_panes = "A2"

    # ---- data rows ----
    for row_idx, issue in enumerate(issues, start=2):
        values = _row(issue)
        for col_idx, val in enumerate(values, start=1):
            cell = ws.cell(row=row_idx, column=col_idx, value=val)

            # Wrap text for summary column (col 5)
            if col_idx == 5:
                cell.alignment = Alignment(wrap_text=True, vertical="top")

            # Color-code priority column (col 2)
            if col_idx == 2:
                priority = val.strip().upper() if val else ""
                if priority in _PRIORITY_FILLS:
                    cell.fill = _PRIORITY_FILLS[priority]
                    cell.font = _PRIORITY_FONTS[priority]
                cell.alignment = Alignment(horizontal="center")

    # ---- auto-width columns ----
    for col_idx in range(1, len(COLUMNS) + 1):
        max_len = len(COLUMNS[col_idx - 1])
        for row_idx in range(2, min(ws.max_row + 1, 200)):  # sample first 200 rows
            val = ws.cell(row=row_idx, column=col_idx).value
            if val:
                # For wrapped columns, use a reasonable cap
                line_len = max(len(l) for l in str(val).split("\n")) if "\n" in str(val) else len(str(val))
                max_len = max(max_len, min(line_len, 80))
        ws.column_dimensions[get_column_letter(col_idx)].width = min(max_len + 3, 60)

    # Summary column should be wider
    ws.column_dimensions[get_column_letter(5)].width = 60

    wb.save(str(out_path))
    return out_path
